# Main k8s Setup
---
- name: Add Nginx-Ingress Helm-Chart repo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
  tags: [k8s, k8-init, k8-ingress, k8s-ingress-nginx]

- name: Deploy Nginx-Ingress
  kubernetes.core.helm:
    name: ingress-nginx
    kubeconfig: /etc/kubernetes/admin.conf
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    wait: true
    values: '{{ k8s_nginx_helm_values }}'
    # state: absent
  tags: [k8s, k8-init, k8-ingress, k8s-ingress-nginx]


