# Promtail config
server:
  disable: true

positions:
  filename: /tmp/promtail-positions.yaml

clients:
  - url: http://mgmt:3100/loki/api/v1/push


scrape_configs:
- job_name: authlog
  static_configs:
  - targets:
      - localhost
    labels:
      job: authlog
      shipper: promtail
      __path__: /var/log/auth.log

- job_name: daemonlog
  static_configs:
  - targets:
      - localhost
    labels:
      job: syslog
      shipper: promtail
      __path__: /var/log/daemon.log

- job_name: daemonlog
  static_configs:
  - targets:
      - localhost
    labels:
      job: syslog
      shipper: promtail
      __path__: /var/log/syslog

- job_name: dpkglog
  static_configs:
  - targets:
      - localhost
    labels:
      job: dpkg
      shipper: promtail
      __path__: /var/log/dpkg.log

- job_name: cronlog
  static_configs:
  - targets:
      - localhost
    labels:
      job: cronlog
      shipper: promtail
      __path__: /var/log/cron.log

- job_name: nginx
  static_configs:
  - targets:
      - localhost
    labels:
      job: nginx
      shipper: promtail
      nginx_host: gateway
      __path__: /var/log/nginx/*.log

  pipeline_stages:
  - match:
      selector: '{job="nginx"}'
      stages:
      # Parse nginx json
      - json:
          expressions:
            nginx_status: status
            nginx_server_name: server_name
            nginx_http_user_agent: http_user_agent
            request:
      # Further disassemble the http request
      - regex:
          expression: '^(?P<nginx_method>[^ ]*) (?P<nginx_request>[^ ]*) (?P<nginx_protocol>[^ ]*)'
          source: request
      # Exported Labels
      - labels:
          nginx_status:
          nginx_server_name:
          nginx_upstream_addr:
          nginx_method:

      # Drop zabbix, nginx prometheus exporter, and health requests
      - drop:
          source:     "nginx_request"
          value:      "/nginx_status"
      - drop:
          source:     "nginx_request"
          value:      "/1.0.0/health"
      - drop:
          source:     "nginx_http_user_agent"
          regex: "Zabbix.*"
