# List pending updates
---
- name: Update apt cache
  apt:
   update_cache: yes

- name: Get upgradable list
  command: apt list --upgradable
  register: main_updates
  changed_when: false

- name: Format update string I
  set_fact:
    updates: '{{ [item | replace("[","") | replace("]","") | replace(",","") ] + updates | default([]) }}'
  loop: '{{ main_updates.stdout_lines[1:] }}'

- name: Format update string II
  run_once: yes
  set_fact:
    all_updates: '{{ all_updates | default({}) | combine({item: hostvars[item].updates}) }}'
  with_items: '{{ groups.all }}'

- name: Print updates
  run_once: yes
  debug:
    var: hostvars[item].updates
  with_items: '{{ groups.all }}'

- name: Save update file to ...
  run_once: yes
  copy:
    content: "{{ all_updates }}"
    dest: /tmp/foobar.txt
  delegate_to: localhost

- name: Upgrade packages
  when: maintenance_run_upgrades | bool
  apt:
    name: '{{ item.split("/")[0] }}'
    state: latest
  loop: '{{ updates }}'

- name: Check for reboot
  stat:
    path: /var/run/reboot-required
  register: main_reboot_needed

- name: Reoot needed?
  debug:
    msg: 'Reboot needed: {{ main_reboot_needed.stat.exists }}'
