# Role maintenance
---
- name: Create and rotate HetznerSnapshots
  when: maintenance_run_hcloud_snapshot | bool
  command: 'node {{ role_path }}/files/hcloude-snapshot.js'
  run_once: yes
  delegate_to: localhost
  register: main_snapshot_res
  tags: [maintenance, backup, db-backup, hetzner-snapshot]


