# Role maintenance
---
- name: System Updates Task
  ansible.builtin.include_tasks: system-updates.yml
  tags: [maintenance, os-updates]

- name: Run Snapshot-Backups
  when: maintenance_run_hcloud_snapshot | bool
  ansible.builtin.include_tasks: hcloud-snapshot.yml
  tags: [maintenance, backup, db-backup, host-backup, hetzner-snapshot]

- name: Run Backup-Scripts
  when: maintenance_run_backup | bool
  ansible.builtin.include_tasks: host-backups.yml
  tags: [maintenance, backup, db-backup]
