# Role maintenance
---

- name: Check updates
  include_tasks: check-updates.yml

- name: Check for DB Backup folder
  stat:
    path: /db_dumps
  register: main_db_dir

- name: List DB dump files older 1 day
  when: main_db_dir.stat.exists
  find:
    paths: /db_dumps
    patterns: '*.dump,'
    age: 1d
    recurse: yes
  register: main_db_files

- name: DB Files
  when: main_db_files
  debug:
    var: main_db_files

- name: Run DB backup script
  when: main_db_dir.stat.exists
  shell: bash /db_dumps/backup_db.sh

# - name: Vault test1
#   debug:
#     var: portainer_pw

# - name: Vault test2
#   debug:
#     var: vault_portainer_pw