# Role maintenance
---
- name: System Updates Task
  include_tasks: system-updates.yml
  tags: [maintenance, updates]

- name: Post updates to GitLab
  when: maintenance_post_to_git | bool
  include_tasks: post-updates.yml
  tags: [maintenance, updates]

- name: Run backup scripts
  when: maintenance_run_hcloud_snapshot | bool
  include_tasks: hcloud-snapshot.yml
  tags: [maintenance, backup, db-backup, host-backup, hetzner-snapshot]

- name: Run backup scripts
  when: maintenance_run_backup | bool
  include_tasks: db-backups.yml
  tags: [maintenance, backup, db-backup]
