# Role maintenance
---
- name: System Updates Task
  include_tasks: system-updates.yml
  tags: [maintenance, os-updates]

- name: Run snapshot-backups
  when: maintenance_run_hcloud_snapshot | bool
  include_tasks: hcloud-snapshot.yml
  tags: [maintenance, backup, db-backup, host-backup, hetzner-snapshot]

- name: Run DB-Backup scripts
  when: maintenance_run_backup | bool
  include_tasks: host-backups.yml
  tags: [maintenance, backup, db-backup]
