- name: Post updates to GitRepo
  when: all_updates is defined
  uri:
    url: '{{ maintenance_git_host }}/api/v4/projects/{{ maintenance_git_repo }}/repository/files/host-updates%2F{{ansible_date_time.iso8601}}-updates.txt'
    method: POST
    body_format: json
    headers:
      PRIVATE-TOKEN: '{{ maintenance_git_token }}'
      Content-Type: application/json
    body:
      branch: main
      author_email: '{{ maintenance_git_mail }}'
      author_name: '{{ maintenance_git_name }}'
      content: '{{ all_updates | to_nice_json }}'
      commit_message: 'Added pending updates on {{ansible_date_time.date}}'
    status_code: 201
  run_once: yes
  ignore_errors: yes
  register: main_reop_logs_res

- name: Create Git issue for updates
  when: all_updates is defined
  uri:
    url: '{{ maintenance_git_host }}/api/v4/projects/{{ maintenance_git_repo }}/issues'
    method: POST
    body_format: form-multipart
    headers:
      PRIVATE-TOKEN: '{{ maintenance_git_token }}'
    body:
      title: '{{ ansible_date_time.date }} System Updates'
      labels: maintenance
      assignee_id: '{{ maintenance_git_assignee_id | string }}'
      description: |
        Updates:
        ```yml
        {{ all_updates | to_nice_yaml }}
        ```
    status_code: 201
  run_once: yes
  ignore_errors: yes
  register: main_reop_issue_res

# - name: Create Git issue for updates
#   when: all_updates is defined
#   uri:
#     url: '{{ maintenance_git_host }}/api/v4/projects/{{ maintenance_git_repo }}/issues?title={{ansible_date_time.date}}%20System%20Updates&labels=maintenance&assignee_id={{ maintenance_git_maintainer }}&description=Updates%3A%0A{{all_updates | to_nice_yaml | urlencode }}'
#     method: POST
#     body_format: json
#     headers:
#       PRIVATE-TOKEN: '{{ maintenance_git_token }}'
#     status_code: 201
#   run_once: yes
#   register: main_reop_issue_res