# Install nginx-hosts and run certbot
---
- name: List sites/host that will be installed
  debug:
    msg:
      - 'Using host: {{ item.host }} with ip: {{ item.ip }}'
      - 'Using locations {{ item.locations | default("location / { proxy_pass http://" + item.host + "_upstream/; }") }}'
      - 'With upstream: {{ item.host }}_upstream { {{item.upstreams | join("\n") }} }'
  loop: '{{ ingress_hosts.sites | default(nginx_default_hosts.sites) }}'
  loop_control:
    label: '{{ item.host }}'
  tags: [ingress, nginx, ingress-hosts]

- name: Copy NGINX conf files
  copy:
    src: '{{ nginx_src_config_dir }}'
    dest: /etc/nginx/
    owner: root
    group: root
    mode: '0644'
  notify: Restart nginx
  tags: [ingress, nginx, ingress-hosts]

- name: Check for dhparam.pem
  stat:
    path: /etc/nginx/dhparam.pem
  register: nginx_dhparam_result
  tags: [ingress, nginx, ingress-hosts]

- name: Creating dhparam.pem
  when: not nginx_dhparam_result.stat.exists
  command: openssl dhparam -out /etc/nginx/dhparam.pem 2048
  tags: [ingress, nginx, ingress-hosts]

- name: Create nginx metrics status page
  template:
    src: internal-status.conf.j2
    dest: /etc/nginx/conf.d/internal-status.conf
    mode: '0644'
  notify: Restart nginx
  tags: [ingress, nginx, ingress-hosts]

- name: Check nginx syntax
  command: nginx -t
  register: res
  changed_when: false
  failed_when: '"warn" is in res.stderr_lines or "emerg" is in res.stderr_lines or res.rc != 0'
  tags: [ingress, nginx, ingress-hosts]

- name: Ensure handlers are notified now
  meta: flush_handlers
  tags: [ingress, nginx, ingress-hosts]

- name: Verify Nginx is started
  service:
    name: nginx
    state: started
  tags: [ingress, nginx, ingress-hosts]

- name: Create directory for dummy certs
  file:
    path: /etc/letsencrypt/dummy
    state: directory
  tags: [ingress, nginx, ingress-hosts]

- name: Copy dummy certs
  copy:
    src: '{{ item }}.dummy'
    dest: '/etc/letsencrypt/dummy/{{ item }}'
    owner: root
    group: root
    mode: '0777'
  loop: ['fullchain.pem', 'privkey.pem']
  tags: [ingress, nginx, ingress-hosts]

- name: Find all nginx hosts
  shell: |
    cd /etc/nginx/conf.d
    ls *.conf
  register: nginx_deployed_hosts
  changed_when: false
  tags: [ingress, nginx, ingress-hosts]

- name: Creating hosts for nginx
  when: nginx_vhost.host + ".conf" not in nginx_deployed_hosts.stdout_lines or nginx_force_reinstall_hosts
  template:
    src: 'site.conf.j2'
    dest: '/etc/nginx/conf.d/{{ nginx_vhost.host }}.conf'
    mode: '0644'
  loop: '{{ ingress_hosts.sites | default(nginx_default_hosts.sites) }}'
  loop_control:
    loop_var: nginx_vhost
    label: '{{ nginx_vhost.host }}'
  vars:
    nginx_settings: '{{ ingress_hosts.conf.nginx | default(nginx_default_hosts.conf.nginx) }}'
  notify: Reload nginx
  register: nginx_created_hosts
  tags: [ingress, nginx, ingress-hosts]

- name: Copy ssl-nginx.conf|ssl-dhparams.pem
  copy:
    src: '{{ item }}'
    dest: '/etc/letsencrypt/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  notify: Reload nginx
  loop: ['options-ssl-nginx.conf', 'ssl-dhparams.pem']
  tags: [ingress, nginx, ingress-hosts]

- name: Check nginx syntax
  command: nginx -t
  register: res
  changed_when: false
  failed_when: '"warn" is in res.stderr_lines or "emerg" is in res.stderr_lines or res.rc != 0'
  tags: [ingress, nginx, ingress-hosts]

- name: Ensure handlers are notified now
  meta: flush_handlers
  tags: [ingress, nginx, ingress-hosts]

- name: Verify Certbot Installation
  when: nginx_run_certbot | bool
  apt:
    name: '{{ item }}'
    state: latest
  loop: [ 'certbot', 'python3-certbot', 'python3-certbot-nginx']
  tags: [ingress, nginx, ingress-hosts]

- name: Run Certbot
  when: nginx_run_certbot | bool and (nginx_created_hosts.changed or nginx_force_reinstall_hosts)
  command: 'certbot --nginx -d {{ nginx_vhost.host }} --agree-tos --non-interactive -m {{ nginx_certbot_mail }} {{"--test-cert" if (nginx_testing_certbot | default(false) ) }}'
  loop: '{{ ingress_hosts.sites | default(nginx_default_hosts.sites) }}'
  loop_control:
    loop_var: nginx_vhost
    label: '{{ nginx_vhost.host }}'
  notify: Reload nginx
  tags: [ingress, nginx, ingress-hosts]

- name: Check nginx syntax
  when: nginx_run_certbot | bool
  command: nginx -t
  register: res
  changed_when: false
  failed_when: '"warn" is in res.stderr_lines or "emerg" is in res.stderr_lines or res.rc != 0'
  tags: [ingress, nginx, ingress-hosts]

- name: Ensure handlers are notified now
  meta: flush_handlers
  tags: [ingress, nginx, ingress-hosts]
