# Install nginx
---
- name: Install nginx on bare-metal
  when: nginx_use_docker | bool != true
  include_tasks: install-nginx-host.yml
  tags: [ingress, nginx]

- name: Install nginx via docker
  when: nginx_use_docker | bool
  include_tasks: install-nginx-docker.yml
  tags: [ingress, nginx]
