# Install nginx
---
- name: Check if docker is installed
  command: docker --version
  register: docker_valid
  ignore_errors: True
  tags: [ingress, nginx]

- name: Run docker install
  when: docker_valid.failed
  include_role:
    name: docker
  vars:
    docker_init_swarm: false
    docker_install_portainer: false
  tags: [ingress, nginx]

