# Install nginx-hosts and run certbot
---

- name: Verify Nginx is started
  service:
    name: nginx
    state: started

- name: Copy Hosts to nginx
  when: nginx_install_hosts | bool
  copy:
    src: '{{ nginx_hosts_src_config_dir }}'
    dest: /etc/nginx/conf.d/
    owner: root
    group: root
    mode: '0644'

- name: Creating example host for nginx
  when: nginx_install_hosts and nginx_hosts_src_config_dir == "example-nginx-hosts/"
  template:
    src: 'site.conf.j2'
    dest: /etc/nginx/conf.d/site.conf
    mode: '0644'

- name: Verify Certbot Installation
  when: nginx_run_certbot | bool
  apt:
    name: '{{ item }}'
    state: latest
  loop: [ 'certbot', 'python3-certbot', 'python3-certbot-nginx']

- name: Run Certbot
  when: nginx_run_certbot | bool
  command: 'certbot --nginx -d {{ nginx_domains | join(",") }} --agree-tos -m {{ nginx_certbot_mail }} -q'

- name: Check nginx syntax
  when: nginx_run_certbot | bool
  command: nginx -t
  register: res
  changed_when: false
  failed_when: '"warn" is in res.stderr_lines or "emerg" is in res.stderr_lines or res.rc != 0'

- name: Reload nginx
  command: nginx -s reload