# Main Nginx Setup
---
- name: Install nginx
  include_tasks: install-nginx.yml

- name: Set floating IPs
  when: nginx_floating_ips | length > 0
  include_tasks: set-floting-ip.yml

- name: Update Promtail config
  when: nginx_update_promtail | bool
  include_tasks: update-promtail.yml

- name: Ensure handlers are notified now
  meta: flush_handlers

- name: Install nginx hosts
  when: nginx_install_hosts | bool
  include_tasks: install-nginx-hosts.yml

- name: Setup cron jobs
  when: nginx_run_certbot | bool
  include_tasks: shared/install-cron-jobs.yml
  vars:
    cron_jobs: '{{ nginx_cron_jobs }}'

- name: Ensure handlers are notified now
  meta: flush_handlers