# Install nginx-hosts and run certbot
---
- name: List sites/host that will be installed
  debug:
    msg:
      - 'Using host: {{ item.host }} with ip: {{ item.ip }}'
      - 'Using locations {{ item.locations | default("location / { proxy_pass http://" + item.host + "_upstream/; }") }}'
      - 'With upstream: {{ item.host }}_upstream { {{item.upstreams | join("\n") }} }'
  loop: '{{ ingress_hosts.sites | default(nginx_default_hosts.sites) }}'
  loop_control:
    label: '{{ item.host }}'
  tags: [ingress, nginx, ingress-hosts]

- name: Copy NGINX conf files
  copy:
    src: nginx/
    dest: /etc/nginx/
    owner: root
    group: root
    mode: '0644'
  tags: [ingress, nginx, ingress-hosts]

- name: Copy NGINX extra conf files
  when: nginx_host_extra_files.stat.exists
  copy:
    src: '{{ inventory_dir }}/{{ inventory_hostname }}/srv/nginx/'
    dest: /etc/nginx/
    owner: root
    group: root
    mode: '0644'
  tags: [ingress, nginx, ingress-hosts]

- name: Check for dhparam.pem
  stat:
    path: /etc/nginx/dhparam.pem
  register: nginx_dhparam_result
  tags: [ingress, nginx, ingress-hosts]

- name: Creating dhparam.pem
  when: not nginx_dhparam_result.stat.exists
  command: openssl dhparam -out /etc/nginx/dhparam.pem 2048
  tags: [ingress, nginx, ingress-hosts]

- name: Create nginx metrics status page
  template:
    src: internal-status.conf.j2
    dest: /etc/nginx/conf.d/internal-status.conf
    mode: '0644'
  tags: [ingress, nginx, ingress-hosts]

- name: Create directory for dummy certs
  file:
    path: /etc/letsencrypt/dummy
    state: directory
  tags: [ingress, nginx, ingress-hosts]

- name: Copy dummy certs
  copy:
    src: '{{ item }}.dummy'
    dest: '/etc/letsencrypt/dummy/{{ item }}'
    owner: root
    group: root
    mode: '0777'
  loop: ['fullchain.pem', 'privkey.pem']
  tags: [ingress, nginx, ingress-hosts]

- name: Find all nginx hosts
  shell: |
    cd /etc/nginx/conf.d
    ls *.conf
  register: nginx_deployed_hosts
  changed_when: false
  tags: [ingress, nginx, ingress-hosts]

- name: Creating hosts for nginx
  when: nginx_vhost.host + ".conf" not in nginx_deployed_hosts.stdout_lines or nginx_force_reinstall_hosts
  template:
    src: 'site.conf.j2'
    dest: '/etc/nginx/conf.d/{{ nginx_vhost.host }}.conf'
    mode: '0644'
  loop: '{{ ingress_hosts.sites | default(nginx_default_hosts.sites) }}'
  loop_control:
    loop_var: nginx_vhost
    label: '{{ nginx_vhost.host }}'
  vars:
    nginx_settings: '{{ ingress_hosts.conf.nginx | default(nginx_default_hosts.conf.nginx) }}'
  register: nginx_created_hosts
  tags: [ingress, nginx, ingress-hosts]

- name: Copy ssl-nginx.conf|ssl-dhparams.pem
  copy:
    src: '{{ item }}'
    dest: '/etc/letsencrypt/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop: ['options-ssl-nginx.conf', 'ssl-dhparams.pem']
  tags: [ingress, nginx, ingress-hosts]


