# Update promtail
---
- name: Copy Promtail config
  ansible.builtin.copy:
    src: '{{ promtail_config_src_path }}'
    dest: '{{ promtail_config_dst_path }}'
    owner: root
    group: root
    mode: '0666'
  notify: Verify Promtail status
  tags: [ingress, ingress-logs]

- name: Enable Promtail service
  ansible.builtin.systemd:
    name: promtail.service
    state: started
    daemon_reload: true
    enabled: true
  tags: [ingress, ingress-logs]
