- name: Create a new databases
  influxdb_database:
    database_name: '{{ item.db }}'
    state: present
    username: '{{ influx_root_user }}'
    password: '{{ influx_root_pw }}'
  loop: '{{ influx_setups }}'
  loop_control:
    label: '{{ item.db }}'
  tags: [influxdb]

- name: Create a user on localhost using default login credentials
  influxdb_user:
    user_name: '{{ item.user }}'
    user_password: '{{ item.pw }}'
    state: present
    login_username: '{{ influx_root_user }}'
    login_password: '{{ influx_root_pw }}'
  loop: '{{ influx_setups }}'
  loop_control:
    label: '{{ item.user }}'
  tags: [influxdb]

- name: Create backup directory if it does not exist
  ansible.builtin.file:
    path: '{{ backup_dir }}'
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags: [influxdb]

- name: Copy backup script
  ansible.builtin.copy:
    src: '{{ influx_db_backup_script }}'
    dest: '{{ backup_dir }}/run_backup.sh'
    owner: root
    group: root
    mode: '0744'
  tags: [influxdb]
