
---
- name: Add influx GPG apt Key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  tags: [influxdb]

- name: Add influx repository
  ansible.builtin.apt_repository:
    repo: deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_facts.lsb.codename }} stable
    update_cache: true
    state: present
    filename: influx
  tags: [influxdb]

- name: Ensure /etc/influxdb2/ directory exists
  ansible.builtin.file:
    path: /etc/influxdb2/
    state: directory
    mode: "0755"
  tags: [influxdb]

- name: Set Influx conf location
  ansible.builtin.lineinfile:
     path: /etc/environment
     line: INFLUXD_CONFIG_PATH=/etc/influxdb2
     create: true
  notify: Reboot
  tags: [influxdb]

- name: Copy influxdb-conf
  ansible.builtin.template:
    src: influxdb.toml.j2
    dest: /etc/influxdb2/influx.toml
    mode: '0644'
  notify: Reload
  tags: [influxdb]

- name: Ensure handlers are notified now
  ansible.builtin.meta: flush_handlers
  tags: [influxdb]

- name: Install Influxdb
  ansible.builtin.apt:
    name: '{{ item }}'
    state: latest
  loop: ['influxdb2', 'influxdb2-cli']
  tags: [influxdb]

- name: Ensure service is started
  ansible.builtin.service:
    name: influxdb
    state: started
    enabled: true
  tags: [influxdb]

- name: Sleep for 15 seconds and continue with play
  ansible.builtin.wait_for:
    timeout: 15
  tags: [influxdb]

- name: Run Influx init
  ansible.builtin.command: 'influx setup --org {{ influx_organization }} --bucket {{ influx_root_bucket }} --username {{ influx_root_user }} --password {{ influx_root_pw }} --host http://{{ influx_listen_addr }} --force'
  register: influx_setup_res
  ignore_errors: true
  tags: [influxdb]
