# Main InfluxDB Setup
---
- name: Install needed packages
  apt:
    name: python3-influxdb
    state: latest
  tags: [influxdb]

- name: Check if Docker is installed
  when: influx_use_docker | bool
  command: docker --version
  register: docker_valid
  ignore_errors: True
  changed_when: False
  tags: [influxdb]

- name: Run Docker install
  when: influx_use_docker | bool and docker_valid.failed | default(True)
  include_role:
    name: docker
  vars:
    docker_init_swarm: false
    docker_install_portainer: false
  tags: [influxdb]

- name: Install Influxdb
  when: influx_use_docker | bool
  include_tasks: install-influxdb-docker.yml
  tags: [influxdb]

- name: Install Influxdb
  when: influx_use_docker | bool == false
  include_tasks: install-influxdb.yml
  tags: [influxdb]

- name: Ensure handlers are notified now
  meta: flush_handlers
  tags: [influxdb]

# Broken right now because influx 2.x
# - name: Init Influxdb
#   include_tasks: init-influxdb.yml
#   tags: [influxdb]

- name: Create backup directory if it does not exist
  file:
    path: /db_dumps
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags: [influxdb]

- name: Copy backup script
  copy:
    src: '{{ influx_db_backup_script }}'
    dest: /db_dumps/backup_db.sh
    owner: root
    group: root
    mode: '0755'
  tags: [influxdb]

- name: Setup cron jobs
  import_tasks: shared/install-cron-jobs.yml
  vars:
    cron_jobs: '{{ influx_cron_jobs }}'
  tags: [influxdb]
