---
- name: Wait for services to come up
  when: docker_deploy_use_swarm_mode and swarm_info.docker_swarm_manager
  ansible.builtin.wait_for:
    timeout: '{{ docker_deploy_wait_timeout }}'
  tags: [docker-deploy]
