# Create users

- name: Create users
  mongodb_user:
    database: '{{ item.db }}'
    login_user: '{{ mongodb_root_user }}'
    login_password : '{{ mongodb_root_pw }}'
    name: '{{ item.user }}'
    password: '{{ item.pw }}'
    state: present
  loop: '{{ mongodb_user_setups }}'


