# Create users

- name: Create users
  mongodb_user:
    database: '{{ item.db }}'
    login_user: '{{ mongodb_root_user | default("root") }}'
    login_password : '{{ mongodb_root_pw }}'
    name: '{{ item.user }}'
    password: '{{ item.pw }}'
    state: '{{ item.state | default("present") }}'
  loop: '{{ mongodb_user_setups }}'
  loop_control:
    label: '{{ item.user }}'

