# Install Mongodb
- name: Add MongoDB apt Key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-5.0.asc
    state: present

- name: Add MongoDB repository
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/debian buster/mongodb-org/5.0 main
    state: present

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Reload mongod systemd
  systemd:
    name: mongod.service
    state: started
    daemon_reload: yes
    enabled: yes

- name: Ensure service is started
  service:
    name: mongod
    state: started
    enabled: yes

