# Main Playbook

- hosts: all
  become: true
  gather_facts: True
  roles:
    - common
    - promtail
    - node-exporter

- hosts: docker_hosts
  become: true
  gather_facts: True
  roles:
    - docker

- hosts: mgmt_hosts
  become: true
  gather_facts: True
  vars_files:
    - '{{ inventory_dir }}/secrets/vault.yml'
  roles:
    - mgmt

- hosts: gateways
  become: true
  gather_facts: True
  roles:
    - nginx

- hosts: minios
  become: true
  gather_facts: True
  roles:
    - minio

- hosts: mariadbs
  become: true
  gather_facts: True
  vars_files:
    - '{{ inventory_dir }}/secrets/vault.yml'
  roles:
    - mariadb

- hosts: mongodbs
  become: true
  gather_facts: True
  vars_files:
    - '{{ inventory_dir }}/secrets/vault.yml'
  roles:
    - mongodb

- hosts: influxdbs
  become: true
  gather_facts: True
  vars_files:
    - '{{ inventory_dir }}/secrets/vault.yml'
  roles:
    - influxdb

- hosts: dev-docker-db
  become: true
  gather_facts: True
  vars_files:
    - '{{ inventory_dir }}/secrets/vault.yml'
  roles:
    - mariadb
    - mongodb
    - influxdb
