auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2021-03-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    shared_store: filesystem
    cache_location: /loki/boltdb-shipper-cache
    active_index_directory: /loki/boltdb-shipper-active
    cache_ttl: 24h
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: loki/boltdb-shipper-compactor
  shared_store: filesystem
  retention_enabled: true

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 72h
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  retention_period: [31d]
  max_streams_per_user: 100000

chunk_store_config:
  max_look_back_period: 721h
