---
##### general #####

# Install extra packages
extra_packages: []

# List of key_paths
ssh_key_list: []

# Key value pairs of hostname: ip
# Default is ansibe_host: ansible_ip
internal_hostnames: []

# List of cron jobs
common_cron_jobs: []
# Example structure
# cron_jobs:
#   - name: Ping Google
#     job: ping google.de
#     weekday: '*'
#     month: '*'
#     minute: '*'
#     hour: '*'
#     day: '24'
#     state: present
#     user: null

