---
##### general #####

# Install extra packages
common_extra_packages: []
common_delete_packages: []
# Floating ips
common_floating_ips: []

# Symbic repo: ssh://git@***REMOVED***:2222/symbic-intern/symbic-authorized-keys.git
common_ssh_key_repo: '{{lookup("env", "SSH_KEY_REPO") | default("none", True)}}'
common_ssh_key_repo_branch: master
# List of key_paths
common_ssh_keys: []
common_ssh_key_dir: data/ssh_keys
common_default_network_device: ens10
# Example
# common_ssh_keys:
#   - filename: '{{ inventory_dir }}/key.pub'
#     state: present                # optional
#     user: root                    # optional
#     key_options: ''               # optional

# Key value pairs of hostname: ip
# Default is ansibe_host: ansible_ip
internal_hostnames: []
# Example
# internal_hostnames:
#   - name: waf-gateway
#     ips:
#       - '10.10.0.2'

# List of cron jobs
common_cron_jobs: []
# Example structure
# cron_jobs:
#   - name: Ping Google
#     job: ping google.de
#     weekday: '*'
#     month: '*'
#     minute: '*'
#     hour: '*'
#     day: '24'
#     state: present
#     user: null

