# K8s install helm

- name: Adding apt GPG Keys
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
  tags: [k8s, k8s-init, k8s-helm]

- name: Add Helm repository
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    update_cache: yes
    state: present
    filename: helm.list
  tags: [k8s, k8s-init, k8s-helm]

- name: Install Helm package
  apt:
    name: helm
    state: present
    update_cache: yes
    install_recommends: no
  tags: [k8s, k8s-init, k8s-helm]

- name: Install Helm Diff
  kubernetes.core.helm_plugin:
    plugin_path: https://github.com/databus23/helm-diff
    state: present
  tags: [k8s, k8s-init, k8s-helm]
