---
# Nginx settings
nginx_src_config_dir: nginx/
nginx_metrics_server_addr: '{{ ansible_default_ipv4.address }}:80'

# Nginx host & Certbot setting
nginx_install_hosts: yes
nginx_force_reinstall_hosts: no
nginx_hosts_default_listen_addr: '{{ ansible_default_ipv4.address }}'
nginx_run_certbot: yes
nginx_certbot_mail: info@xyz.com
nginx_testing_certbot: no # if yes use letsencrypt staging (no rate limit)

# Domain settings
nginx_vhosts:
  - host: example.123preview.com
    ip: '{{ nginx_hosts_default_listen_addr }}'
    upstream: |
      upstream my_upstream {
        server localhost:500;
      }
    locations: |
      location / {
        return 404;
      }

# Common Headders to use are:
#proxy_set_header Host $host;
#proxy_set_header X-Real-IP $remote_addr;
#proxy_set_header X-Forwarded-Protocol  $scheme;
#proxy_set_header X-Forwarded-For $remote_addr;

# Floating IPs
nginx_floating_ips: []
nginx_firewall_rules: []

# Update promtail
nginx_update_promtail: yes
promtail_config_src_path: promtail-config.yml
promtail_config_dst_path: /srv/promtail/promtail-config.yml

# For cert renew
nginx_cron_jobs:
  - name: Certbot renew
    job: echo "certbot renew" >> /var/log/cron.log && certbot renew >> /var/log/cron.log
    weekday: '2'
    month: '*'
    minute: '30'
    hour: '02'
    day: '*'
    state: present
    user: null

nginx_default_firewall_rules:
  - name: Setup public net
    zone: public
    interface: eth0
  - name: https
    service: https
    zone: public
  - name: http
    service: http
    zone: public
  - name: Setup internal net
    zone: internal
    interface: ens10
    sourceips: 10.10.0.0/24
  - name: node-exporter
    zone: internal
    port: 9100/tcp
  - name: http-internal
    zone: internal
    port: 80/tcp
  - name: https-internal
    zone: internal
    port: 443/tcp
