# Main k8s Setup
---
- name: Enable and check kubelet service
  debug:
    var: k8_join_command
  tags: [k8s, k8s-init, k8s-join]

- name: Check if kubeadm has already run
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: k8s_kubeadm_worker_ca
  tags: [k8s, k8-init, k8s-join]

- name: Join Nodes
  when: '"k8s_worker" in group_names and not k8s_kubeadm_worker_ca.stat.exists'
  command: '{{ k8_join_command }}'
  tags: [k8s, k8s-init, k8s-join]
  register: k8s_join_res

- name: Enable and check kubelet service
  debug:
    var: k8s_join_res
  tags: [k8s, k8s-init, k8s-join]
