---
# Traefik settings
ingress_hosts_file: null
ingress_hosts: '{{lookup("file", ingress_hosts_file) | from_yaml if(ingress_hosts_file) }}'

traefik_use_docker: yes
traefik_docker_version: v2.6

# Nginx host & Certbot setting
traefik_install_hosts: yes
traefik_hosts_default_listen_addr: '{{ ansible_default_ipv4.address }}'
traefik_run_certbot: yes
traefik_certbot_mail: info@xyz.com

# Floating IPs
ingress_floating_ips: []
traefik_firewall_rules: []

# Example site conf
traefik_default_hosts:
  conf:
    traefik:
      middlewares:
        auth:
          basicAuth:
            users:
              - "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/"
        testHeader:
          headers:
            customResponseHeaders:
              X-Custom-Response-Header: "value"
  sites:
    - host: default.example.123preview.com
      ip: '{{ ansible_default_ipv4.address }}'
      upstreams: [127.0.0.1:3000]
      traefik:
        protocol: http
        middlewares: [auth, testHeader]
    - host: custom.example.123preview.com
      ip: '{{ ansible_default_ipv4.address }}'
      upstreams: [127.0.0.1:3000]
