# K8s install certmanager

# TODO make sure helm is installed
- name: Add Certmanager Helm-Chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-certmanager]

- name: Deploy Cert manager
  kubernetes.core.helm:
    name: cert-manager
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
    chart_version: v1.7.1
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    update_repo_cache: true
    wait: true
    values: '{{ k8s_certmanager_helm_values | default({}) }}'
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-certmanager]

- name: Ensure Cert Manager Manifest directory exists
  ansible.builtin.file:
    path: /srv/certmanager
    state: directory
    mode: 0755
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-certmanager]

- name: Copy Certmanager Manifests
  when: k8s_certmanager_letsencrypt_mail != "none"
  template:
    src: '{{ item }}.j2'
    dest: '/srv/certmanager/{{ item }}'
    mode: '0644'
  loop: [lets-encrypt-issuer-staging.yml, lets-encrypt-issuer-prod.yml]
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-certmanager]

- name: Apply Certmanager Manifests
  when: k8s_certmanager_letsencrypt_mail != "none"
  k8s:
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
    state: present
    src: '/srv/certmanager/{{ item }}'
  run_once: true
  loop: [lets-encrypt-issuer-staging.yml, lets-encrypt-issuer-prod.yml]
  tags: [k8s, k8-init, k8-master-init, k8-cri, k8-weave]
