# k8s join
---
- name: Test reachability to shared KubeControlPlaneHost
  shell: 'ping -c 5 {{ k8s_shared_api_server_endpoint }}'
  changed_when: false
  tags: [k8s, k8s-init, k8s-join, k8s-worker-join]

- name: Get Worker join command
  command: kubeadm token create --print-join-command
  register: k8_worker_join_command_res
  run_once: true
  changed_when: false
  delegate_to: '{{ groups.k8s_master | flatten | first }}'
  tags: [k8s, k8s-init, k8s-join, k8s-worker-join]

- name: Debug - Print join command
  debug:
    msg: |
      {{ k8_worker_join_command_res.stdout }} \
        --apiserver-advertise-address={{ ansible_facts.all_ipv4_addresses | ansible.utils.reduce_on_network(k8s_cloud_subnet) | first if(k8s_cloud_subnet | default("none") != "none") else k8s_kubelet_advertise_address_bind | default(ansible_facts.default_ipv4.address) }}
  tags: [k8s, k8-init, k8-master-init, k8s-worker-join]

- name: Check if kubeadm has already run
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: k8s_kubeadm_worker_ca
  tags: [k8s, k8-init, k8s-join, k8s-worker-join]

- name: Join Nodes
  when: not k8s_kubeadm_worker_ca.stat.exists
  command: '{{ k8_worker_join_command_res.stdout }} --apiserver-advertise-address={{ ansible_facts.all_ipv4_addresses | ansible.utils.reduce_on_network(k8s_cloud_subnet) | first if(k8s_cloud_subnet | default("none") != "none") else k8s_kubelet_advertise_address_bind | default(ansible_facts.default_ipv4.address) }}'
  tags: [k8s, k8s-init, k8s-join, k8s-worker-join]
  register: k8s_join_res

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  tags: [k8s, k8s-init, k8s-join, k8s-worker-join]

- name: Debug - Print join res
  debug:
    var: k8s_join_res
  tags: [k8s, k8s-init, k8s-join, k8s-worker-join]
