# Install & Setup SimpleProxy
---
- name: Check if simpleproxy is installed
  ansible.builtin.command: 'which simpleproxy'
  register: simpleproxy_check_result
  changed_when: false
  failed_when: false
  tags: [simpleproxy]

- name: Install simpleproxy
  when: '"non-zero return code" in simpleproxy_check_result.msg'
  ansible.builtin.apt:
    name: simpleproxy
    state: latest
    update_cache: true
    install_recommends: false
  tags: [simpleproxy]

- name: Test simpleproxy
  ansible.builtin.command: "simpleproxy -V"
  changed_when: "false"
  tags: [simpleproxy]

- name: Add simpleproxy user
  user:
    name: simpleproxy
    ansible.builtin.shell: /usr/sbin/nologin
    create_home: false
    system: true
    state: present
  tags: [simpleproxy]

- name: Adding simpleproxy service
  ansible.builtin.include_tasks: service.yml
  loop: '{{ simpleproxy_confs }}'
  loop_control:
    loop_var: simpleproxy_conf
  tags: [simpleproxy]
