---
- name: Restart SSHD
  ansible.builtin.service:
    name: sshd
    enabled: true
    state: reloaded
  tags: [mgmt, ssh]

- name: Reload nginx
  community.docker.docker_container_exec:
    container: '{{ nginx_containerid.stdout }}'
    ansible.builtin.command: /bin/sh -c "nginx -t && nginx -s reload"
  register: result
  tags: [mgmt, mgmt-stack, mgmt-nginx]

- name: Restart network service
  ansible.builtin.service:
    name: networking
    state: restarted
  tags: [mgmt]

- name: Restart network ubuntu service
  ansible.builtin.command: netplan apply
  tags: [mgmt]
