---
# SQL settings

# Install via docker
mariadb_use_docker: true
mariadb_docker_version: 10.7

# Init
mariadb_root_user: root
mariadb_root_pw: null
sql_db_socket: "{{'' if (mariadb_use_docker) else '/var/run/mysqld/mysqld.sock'}}"

sql_db_backup_script: "{{'backup_db-docker.sh' if (mariadb_use_docker) else 'backup_db-docker.sh'}}"

# DB setup
sql_setups:
  - db: test1
    user: user1
    pw: mysecurepw1
  - db: test2
    user: user2
    pw: mysecurepw2

# For backup
backup_dir: /backup_dumps
mariadb_cron_jobs:
  - name: Dump DB as backup
    job: 'CUSTOM_BACKUP_DIR={{ backup_dir }} bash {{ backup_dir }}/run_backup.sh'
    weekday: '*'
    month: '*'
    minute: '30'
    hour: '02'
    day: '*'
    state: present
    user: null
