

- name: Collect all possible information of DB
  mysql_info:
    login_user: '{{ mariadb_root_user }}'
    login_password : '{{ mariadb_root_pw }}'
    login_unix_socket: '{{ sql_db_socket }}'

- name: Create a new databases
  mysql_db:
    login_user: '{{ mariadb_root_user }}'
    login_password : '{{ mariadb_root_pw }}'
    name: '{{ item.db }}'
    state: present
    login_unix_socket: '{{ sql_db_socket }}'
    login_host: localhost
  loop: '{{ sql_setups }}'
  loop_control:
    label: '{{ item.db }}'

- name: Create Users.
  mysql_user:
    login_user: '{{ mariadb_root_user }}'
    login_password : '{{ mariadb_root_pw }}'
    name: '{{ item.user }}'
    password: '{{ item.pw }}'
    state: '{{ item.state | default("present") }}'
    login_unix_socket: '{{ sql_db_socket }}'
  loop: '{{ sql_setups }}'
  loop_control:
    label: '{{ item.user }}'

- name: Create backup directory if it does not exist
  file:
    path: /db_dumps
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Copy backup script
  copy:
    src: '{{ sql_db_backup_script }}'
    dest: /db_dumps/backup_db.sh
    owner: root
    group: root
    mode: '0744'

