
- name: Install MariaDB
  apt:
    name: '{{ item }}'
    state: latest
    update_cache: yes
  loop: ['mariadb-server', 'python3-pymysql']

- name: Ensure service is started
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Sleep for 15 seconds and continue with play
  wait_for:
    timeout: 15

- name: Check if root password is set
  shell: |
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check

- name: Set MariaDB root password for the first time
  mysql_user:
    name: '{{ sql_root_user }}'
    password: "{{ mariadb_root_pw }}"
    state: present
    login_unix_socket: '{{ sql_db_socket }}'
  when: root_pwd_check.rc == 0