# Main Mariadb Setup
---
- name: Install needed packages
  apt:
    name: python3-pymysql
    state: latest
  tags: [mariadb]

- name: Run Docker install
  when: mariadb_use_docker | bool
  include_role:
    name: docker
  vars:
    docker_init_swarm: false
    docker_install_portainer: false
  tags: [mariadb]

- name: Install MariaDB
  when: mariadb_use_docker | bool
  include_tasks: install-mariadb-docker.yml
  tags: [mariadb]

- name: Install MariaDB
  when: mariadb_use_docker | bool == false
  include_tasks: install-mariadb.yml
  tags: [mariadb]

- name: Init MariaDB
  import_tasks: init-mariadb.yml
  tags: [mariadb]

- name: Setup cron jobs
  import_tasks: shared/install-cron-jobs.yml
  vars:
    cron_jobs: '{{ mariadb_cron_jobs }}'
  tags: [mariadb, cron]

- name: Create backup directory if it does not exist
  file:
    path: ' {{ backup_dir }}'
    state: directory
    mode: '0755'
    owner: root
    group: root
  tags: [mariadb]

- name: Copy backup script
  copy:
    src: '{{ sql_db_backup_script }}'
    dest: '{{ backup_dir }}/run_backup.sh'
    owner: root
    group: root
    mode: '0755'
  tags: [mariadb]
