# Main Mariadb Setup
---
- name: Install needed packages
  apt:
    name: python3-pymysql
    state: latest

- name: Run docker install
  when: mariadb_use_docker | bool
  include_role:
    name: docker
  vars:
    docker_init_swarm: false
    docker_install_portainer: false

- name: Install MariaDB
  when: mariadb_use_docker | bool
  include_tasks: install-mariadb-docker.yml

- name: Install MariaDB
  when: mariadb_use_docker | bool == false
  include_tasks: install-mariadb.yml

- name: Init MariaDB
  include_tasks: init-mariadb.yml

- name: Setup cron jobs
  include_tasks: shared/install-cron-jobs.yml
  vars:
    cron_jobs: '{{ mariadb_cron_jobs }}'

- name: Create backup directory if it does not exist
  file:
    path: /db_dumps
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Copy backup script
  copy:
    src: '{{ sql_db_backup_script }}'
    dest: /db_dumps/backup_db.sh
    owner: root
    group: root
    mode: '0755'
