---
- name: Restart network service
  ansible.builtin.service:
    name: networking
    state: restarted

- name: Restart network ubuntu service
  ansible.builtin.command: netplan apply

- name: Verify Promtail status
  ansible.builtin.service:
    name: promtail
    state: restarted

- name: Reload nginx
  ansible.builtin.command: nginx -s reload

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: Restart firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
