---
- name: Restart network service
  service:
    name: networking
    state: restarted

- name: Verify promtail status
  service:
    name: promtail
    state: restarted

- name: Reload nginx
  command: nginx -s reload

- name: Restart nginx
  service:
    name: nginx
    state: restarted
