# Main Docker deploy
---
- name: Install pip3
  when: docker_deploy_use_swarm_mode | bool != true
  apt:
    name: python3-pip
    state: latest
  tags: [docker-deploy]

# May need gcc make python3-dev gcc-multilib libffi-dev
- name: Install compose package
  when: docker_deploy_use_swarm_mode | bool != true
  pip:
    name: docker-compose
  tags: [docker-deploy]

- name: Get the info on Docker host
  docker_swarm_info:
  ignore_errors: True
  register: swarm_info
  failed_when: 'not swarm_info.can_talk_to_docker'
  tags: [docker-deploy]

- name: Init a new swarm
  when: docker_deploy_use_swarm_mode | bool and not swarm_info.docker_swarm_manager and docker_deploy_projects | length > 0
  docker_swarm:
    advertise_addr: '{{ ansible_host }}'
    state: present
  tags: [docker-deploy]

- name: Log into Docker registries
  docker_login:
    registry_url: '{{ item.regestry | default("https://index.docker.io/v1/") }}'
    username: '{{ item.username }}'
    password: '{{ item.password }}'
    reauthorize: yes
  loop: '{{ docker_regesties }}'
  loop_control:
    label: '{{ item.regestry | default("https://index.docker.io/v1/") }}'
  tags: [docker-deploy]

- name: Synchronization of application compose|stack files
  become: False
  synchronize:
    src: '{{ docker_deploy_src_config_files }}'
    dest: '{{ docker_deploy_dst_config_files }}'
    recursive: yes
    use_ssh_args: yes
    mode: push
    checksum: yes
    rsync_opts: '{{ docker_deploy_rsync_args }}'
  tags: [docker-deploy]

- name: Using override-file with the following content
  debug:
    var: docker_deploy_override
  tags: [docker-deploy, docker-deploy-stack]

- name: Copy backup script
  when: docker_deploy_backup_script | default("none") != "none"
  copy:
    src: '{{ docker_deploy_backup_script }}'
    dest: '{{ backup_dir }}/run_backup.sh'
    owner: root
    group: root
    mode: '0755'
  tags: [docker-deploy]

- name: Check for auto generated files
  stat:
    path: '{{ item.file }}'
  loop: '{{ docker_deploy_generated_files }}'
  loop_control:
    label: '{{ item.file }}'
  register: docker_deploy_gen_files
  tags: [docker-deploy]

- name: Initial directory creation for generated files
  when: not item.stat.exists
  file:
    state: directory
    path: '{{ item.item.file | dirname }}'
  loop: '{{ docker_deploy_gen_files.results | default([]) }}'
  loop_control:
    label: '{{ item.item.file }}'
  tags: [docker-deploy]

- name: Initial copy for auto generated files
  when: not item.stat.exists
  copy:
    content: '{{ item.item.content }}'
    dest: '{{ item.item.file }}'
  loop: '{{ docker_deploy_gen_files.results | default([]) }}'
  loop_control:
    label: '{{ item.item.file }}'
  tags: [docker-deploy]

- name: Fix file permissions
  file:
    path: '{{ docker_deploy_dst_config_files + item.name }}'
    owner: root
    group: root
    mode: '{{ item.mode | default("0644") }}'
  loop: '{{ docker_deploy_file_permissions }}'
  tags: [docker-deploy]

- name: Create a artifact directory
  delegate_to: localhost
  become: False
  run_once: True
  file:
    dest: '{{ docker_deploy_artifact_dir }}'
    state: directory
  tags: [docker-deploy]

- name: Deploy Apps via Docker-Service-CLI
  include_tasks: doploy-service.yml
  tags: [docker-deploy, docker-deploy-service]

- name: Deploy Apps via Docker-Compose-File
  include_tasks: deploy-stack.yml
  loop: '{{ docker_deploy_projects }}'
  loop_control:
    loop_var: docker_project
  tags: [docker-deploy, docker-deploy-stack]

- name: Get stack info
  when: docker_deploy_use_swarm_mode | bool and swarm_info.docker_swarm_manager
  community.docker.docker_stack_info:
  register: app_docker_stack_info
  tags: [docker-deploy]

- name: Get info on Docker Swarm
  changed_when: False
  when: docker_deploy_use_swarm_mode | bool and swarm_info.docker_swarm_manager
  command: docker service ls
  ignore_errors: True
  register: app_docker_swarm_info
  tags: [docker-deploy]

- name: Get info on Docker Containers
  changed_when: False
  command: 'docker ps --format "table {{ "{{" }}.Status{{ "}}" }}\t{{ "{{" }}.RunningFor{{ "}}" }}\t{{ "{{" }} .Image{{ "}}" }}\t{{ "{{" }}.Names{{ "}}" }}"'
  ignore_errors: True
  register: app_docker_container_info
  tags: [docker-deploy]

- name: Show stack info
  when: docker_deploy_use_swarm_mode | bool and swarm_info.docker_swarm_manager
  debug:
    var: app_docker_stack_info.results
  tags: [docker-deploy]

- name: Print Swarm Info
  when: docker_deploy_use_swarm_mode | bool and swarm_info.docker_swarm_manager
  debug:
    var: app_docker_swarm_info.stdout_lines
  ignore_errors: True
  tags: [docker-deploy]

- name: Show container info
  debug:
    var: app_docker_container_info.stdout_lines
  tags: [docker-deploy]
