---
- name: Update grub
  command: update-grub2
  tags: [common, sys]

- name: Restart network service
  service:
    name: networking
    state: restarted

- name: Restart network ubuntu service
  command: netplan apply