---
- name: Update grub
  ansible.builtin.command: update-grub2
  tags: [common, sys]

- name: Restart network service
  ansible.builtin.service:
    name: networking
    state: restarted

- name: Restart network ubuntu service
  ansible.builtin.command: netplan apply

- name: Restart SSHD
  ansible.builtin.service:
    name: sshd
    enabled: true
    state: reloaded
  tags: [mgmt, ssh]
