- name: Adding apt GPG Keys
  apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present
  tags: [k8s, k8s-init, k8s-helm]

- name: Add helm repository
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    update_cache: yes
    state: present
    filename: helm.list
  tags: [k8s, k8s-init, k8s-helm]

- name: Install helm package
  apt:
    name: helm
    state: present
    update_cache: yes
    install_recommends: no
  tags: [k8s, k8s-init, k8s-helm]
