# K8s install certmanager

- name: Add Certmanager Helm-Chart repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-certmanager]

- name: Deploy Cert manager
  kubernetes.core.helm:
    name: cert-manager
    kubeconfig: /etc/kubernetes/admin.conf
    chart_version: v1.7.1
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    wait: true
    values: '{{ k8s_certmanager_helm_values }}'
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-certmanager]