# Main k8s Setup
---
- name: Check if kubeadm has already run
  when: '"k8s_master" in group_names'
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca
  tags: [k8s, k8-init, k8-master-init]

- name: Init cluster if needed
  include_tasks: kubeadm-init.yml
  when: '"k8s_master" in group_names and not kubeadm_ca.stat.exists'
  run_once: true
  tags: [k8s, k8-init, k8-master-init]

- name: Enable and check kubelet service
  systemd:
    name: kubelet
    daemon_reload: yes
    state: started
    enabled: yes
  tags: [k8s, k8-init, k8-master-init]

- name: Setup CNI and Ingress
  when: '"k8s_master" in group_names'
  include_tasks: setup-cni-and-ingress.yml
  run_once: true
  tags: [k8s, k8-init, k8-master-init, k8-cri, k8-ingress]

- name: Setup configs
  when: '"k8s_master" in group_names'
  include_tasks: setup-cni-and-ingress.yml
  run_once: true
  tags: [k8s, k8-init, k8-master-init]

- name: Install Helm
  when: '"k8s_master" in group_names and k8s_install_helm'
  include_tasks: install-helm.yml
  run_once: true
  tags: [k8s, k8s-init, k8s-helm]

- name: Get Join Command
  when: '"k8s_master" in group_names'
  command: kubeadm token create --print-join-command
  register: tmp_k8_join_command
  tags: [k8s, k8s-init, k8s-join]

- name: Setting Join command for all nodes
  when: '"k8s_master" in group_names'
  run_once: true
  set_fact:
    k8_join_command: '{{ tmp_k8_join_command.stdout }}'
  delegate_to: "{{ item }}"
  with_items: "{{ play_hosts }}"
  tags: [k8s, k8s-init, k8s-join]

# - name: Kubeadm check
#   shell: kubectl cluster-info
#   tags: [k8s, k8s-prepare, k8s-base]


# - name: Ensure handlers are notified now
#   meta: flush_handlers

