# Main k8s Setup

# - name: Add rancher chart repo
#   kubernetes.core.helm_repository:
#     name: rancher-stable
#     repo_url: "https://releases.rancher.com/server-charts/stable"
#   tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-helm-rancher]

# - name: Add certmanager chart repo
#   kubernetes.core.helm_repository:
#     name: jetstack
#     repo_url: "https://charts.jetstack.io"
#   tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-helm-rancher]

# - name: Deploy Cert manager
#   kubernetes.core.helm:
#     name: cert-manager
#     chart_version: v1.7.1
#     chart_ref: jetstack/cert-manager
#     release_namespace: cert-manager
#     create_namespace: true
#     wait: true
#     values:
#       installCRDs: true
#   tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-helm-rancher]

- name: Create a monitoring namespace
  kubernetes.core.k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: present
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-helm-rancher]

- name: Copy monitoring definitions files
  copy:
    src: files/monitoring/
    dest: /srv/monitoring
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-helm-rancher, k8s-monitor]

- name: Apply Grafana Agent Manifest & K8s Dashboad
  k8s:
    namespace: monitoring
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    src: '{{ item }}'
  loop:
    - /srv/monitoring/grafana-metrics-config.yml
    - /srv/monitoring/grafana-metrics-agent.yml
    - /srv/monitoring/grafana-log-config.yml
    - /srv/monitoring/grafana-log-agent.yml
    - /srv/monitoring/grafana-traces-config.yml
    - /srv/monitoring/grafana-traces-agent.yml
    - /srv/monitoring/k8s-dashboard.yml
    - /srv/monitoring/k8s-dashboard-user.yml
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-helm-rancher, k8s-monitor]


# From repository
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: '{{ item.name }}'
    repo_url: '{{ item.url }}'
  with_items:
    - { name: prometheus-community, url: https://prometheus-community.github.io/helm-charts }
    - { name: rancher-stable, url: https://releases.rancher.com/server-charts/stable }
  tags: [k8s, k8-init, k8s-monitor]


- name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
  kubernetes.core.helm:
    name: ksm
    chart_ref: prometheus-community/kube-state-metrics
    update_repo_cache: true
    release_namespace: monitoring
    create_namespace: true
    values:
      image:
        tag: v2.4.2
  tags: [k8s, k8-init, k8s-monitor]



- name: Create a Rancher namespace
  kubernetes.core.k8s:
    name: cattle-system
    api_version: v1
    kind: Namespace
    state: present
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-helm-rancher]
