# Main k8s Setup
- name: Download network CNI manifest
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: ~/cri-flannel.yml
    mode: '0664'
  tags: [k8s, k8-init, k8-master-init, k8-cri, k8-flannel]

- name: Apply flannel-cri manifest to the cluster
  k8s:
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
    state: present
    src: ~/cri-flannel.yml
  run_once: true
  tags: [k8s, k8-init, k8-master-init, k8-cri, k8-flannel]
