# Main k8s Setup
- name: Download network CNI manifest
  get_url:
    url: https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
    dest: ~/cri-weave.yml
    mode: '0664'
  tags: [k8s, k8-init, k8-master-init, k8-cri, k8-weave]

- name: Apply weave-cri manifest to the cluster
  k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    src: ~/cri-weave.yml
  run_once: true
  tags: [k8s, k8-init, k8-master-init, k8-cri, k8-weave]
