# Main k8s Monitoring

- name: Create a monitoring namespace
  kubernetes.core.k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: present
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-helm-rancher]

- name: Copy monitoring definitions files
  copy:
    src: files/monitoring/
    dest: /srv/monitoring
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-helm-rancher, k8s-monitor]

- name: Apply Grafana Agent Manifest & K8s Dashboad
  k8s:
    namespace: monitoring
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    src: '{{ item }}'
  loop:
    - /srv/monitoring/grafana-metrics-config.yml
    - /srv/monitoring/grafana-metrics-agent.yml
    - /srv/monitoring/grafana-log-config.yml
    - /srv/monitoring/grafana-log-agent.yml
    - /srv/monitoring/grafana-traces-config.yml
    - /srv/monitoring/grafana-traces-agent.yml
    - /srv/monitoring/k8s-dashboard.yml
    - /srv/monitoring/k8s-dashboard-user.yml
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-helm-rancher, k8s-monitor]

- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-helm-rancher, k8s-monitor]

- name: Deploy latest version of Prometheus chart inside monitoring namespace (and create it)
  kubernetes.core.helm:
    name: ksm
    chart_ref: prometheus-community/kube-state-metrics
    update_repo_cache: true
    release_namespace: monitoring
    create_namespace: true
    values:
      image:
        tag: v2.4.2
  tags: [k8s, k8-init, k8-master-init, k8-helm, k8s-helm-rancher, k8s-monitor]