# Main k8s Setup
- name: Download network CNI manifest
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    dest: ~/cri-flannel.yaml
    mode: '0664'
  tags: [k8s, k8-init, k8-master-init, k8-cri]

- name: Apply flannel-cri manifest to the cluster
  k8s:
    kubeconfig: /etc/kubernetes/admin.conf
    state: present
    src: ~/cri-flannel.yaml
  run_once: true
  tags: [k8s, k8-init, k8-master-init, k8-cri]

