---
# SQL settings

# Install via docker
mongodb_use_docker: yes
mongodb_docker_version: 4.4-focal
mongodb_docker_use_swarm: no

# Init
mongodb_command_agrs: '""'
mongo_src_config_files: srv
mongodb_root_user: root
mongodb_root_pw: MySuperSecurePW

# Backup
mongodb_db_backup_script: "{{'backup_db-docker.sh' if (mongodb_use_docker) else 'backup_db-docker.sh'}}"

# DB setup
mongodb_user_setups: []
# Example
# mongodb_user_setups:
#   - db: admin
#     user: user1
#     pw: mysecurepw1
#     state: present # Optional

# For backup
backup_dir: /backup_dumps
mongodb_cron_jobs:
  - name: Dump DB as backup
    job: 'CUSTOM_BACKUP_DIR={{ backup_dir }} bash {{ backup_dir }}/run_backup.sh'
    weekday: '*'
    month: '*'
    minute: '30'
    hour: '02'
    day: '*'
    state: present
    user: null
