---
# SQL settings

# Install via docker
mongodb_use_docker: yes
mongodb_docker_version: 4.4-focal

# Init
mongodb_root_user: root
mongodb_root_pw: MySuperSecurePW

# Backup
mongodb_db_backup_script: "{{'backup_db-docker.sh' if (mongodb_use_docker) else 'backup_db-docker.sh'}}"

# DB setup
mongodb_user_setups:
  - db: admin
    user: user1
    pw: mysecurepw1
    state: present # Optional

# For backup
mongodb_cron_jobs:
  - name: Dump DB as backup
    job: bash /db_dumps/backup_db.sh
    weekday: '*'
    month: '*'
    minute: '30'
    hour: '02'
    day: '*'
    state: present
    user: null
