global:
  checkNewVersion: true
  sendAnonymousUsage: false

# entryPoints:
#   web:
#     address: :80
#   websecure:
#     address: :443

log:
  level: DEBUG
  format: json
  filePath: /var/log/traefik/traefik.log

accessLog:
  format: json
  filePath: /var/log/traefik/access.log

api:
 insecure: true
 dashboard: true

providers:
  file:
    directory: /srv/traefik/hosts
    watch: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true

certificatesResolvers:
  traefik_ssl_resolver:
    acme:
      email: info@***REMOVED***
      storage: /srv/traefik/tls
      httpChallenge:
        entryPoint: web_b742f2d905e8c3c1e1f726de1bcfbe0f