# settings

# Configurable
backup_dir: /backup_dumps
maintenance_run_backup: yes
maintenance_post_to_git: yes
maintenance_run_hcloud_snapshot: no
maintenance_run_upgrades: '{{ lookup("env", "ANSIBE_RUN_UPDATES") | default("no", True) | bool }}'
maintenance_git_token: '{{ lookup("env", "GITLAB_API_TOKEN") | default("***REMOVED***", True) }}'
maintenance_git_host: https://***REMOVED***
maintenance_git_repo: '{{ lookup("env", "CI_LOG_PROJECT_ID") | default("177", True) }}'
maintenance_git_branch: main
maintenance_git_name: Gitlab CI
maintenance_git_mail: git-ci@***REMOVED***
maintenance_git_assignee_id: '{{ lookup("env", "GITLAB_USER_ID") | default("13", True) }}' # Henrik Gerdes
maintenance_mattermost_hook: https://mattermost.***REMOVED***/hooks/dyqdgdsncfbbpqif1eyba96d5r

maintenance_hold_back_updates: '{{ lookup("env", "ANSIBE_HOLD_BACK_UPDATES") | default("", True) | from_yaml | list }}'

# Internal
main_backup_dir: '{{ backup_dir if(backup_dir | last == "/") else backup_dir + "/" }}'
