# settings

# Configurable
backup_dir: /backup_dumps
maintenance_run_backup: true
maintenance_post_to_git: true
maintenance_run_hcloud_snapshot: false
maintenance_run_upgrades: '{{ lookup("env", "ANSIBE_RUN_UPDATES") | default("no", true) | bool }}'
maintenance_git_token: '{{ lookup("env", "GITLAB_API_TOKEN") | default("***REMOVED***", true) }}'
maintenance_git_host: https://gitlab.com
maintenance_git_repo: '{{ lookup("env", "CI_LOG_PROJECT_ID") | default("177", true) }}'
maintenance_git_branch: main
maintenance_git_name: Gitlab CI
maintenance_git_mail: git-ci@exmple.com
maintenance_git_assignee_id: '{{ lookup("env", "GITLAB_USER_ID") | default("13", true) }}' # Henrik Gerdes
maintenance_mattermost_hook: '{{ lookup("env", "MM_WEB_HOOK") | default("https://mattermost.com/hooks/dyqdgdsncfbbpqif1eyba96d5r", true) }}'

maintenance_hold_back_updates: '{{ lookup("env", "ANSIBE_HOLD_BACK_UPDATES") | default("[]", true) | from_yaml | list }}'

# Internal
main_backup_dir: '{{ backup_dir if (backup_dir | last == "/") else backup_dir + "/" }}'
