---
# Deploy app via Docker

# Use stack deploy mode or compose mode
docker_deploy_use_swarm_mode: no
docker_deploy_src_config_files: srv/
docker_deploy_dst_config_files: /srv/
docker_deploy_override_file: docker-deploy-override.yml
docker_deploy_override: '{{ lookup("file", docker_deploy_override_file) | from_yaml }}'
docker_deploy_prune_old_services: no
docker_deploy_app_name: myapp
docker_deploy_conf_version: '{{ lookup("env","CI_COMMIT_SHORT_SHA") | default(ansible_date_time.iso8601_basic_short, True) }}'
docker_deploy_tag: latest

docker_deploy_services: []
docker_deploy_stacks: []

docker_deploy_generated_files: []
# Example
# docker_deploy_generated_files:
#   - file: my-file-path
#     content: '{{ lookup("file", docker_deploy_src_config_files + "my-file-path") }}'

docker_deploy_rsync_args: []
# Example
# docker_deploy_rsync_args:
#   - "--exclude=.git"

docker_deploy_file_permissions: []
# Example
# docker_deploy_file_permissions:
#   - name: application.json
#     mode: 0666

docker_regesties: []
# Example
# docker_regesties:
#   - regestry: index.docker.io/v1/
#     username: MyUser
#     password: MySuperSecurPW