---
# Deploy app via Docker

# Use stack deploy mode or compose mode
docker_deploy_use_swarm_mode: no
docker_deploy_src_config_files: srv/
docker_deploy_dst_config_files: /srv/
docker_deploy_app_name: myapp

docker_deploy_services_to_install:
  - docker-compose.yml

docker_regesties: []
# Example
# docker_regesties:
#   - regestry: index.docker.io/v1/
#     username: MyUser
#     password: MySuperSecurPW