# Role firwalld
---
- name: Install firewalld
  apt:
    name: firewalld
    state: latest
    update_cache: yes
  tags: [firewall, firewalld]

- name: Enable firewalld service
  systemd:
    name: firewalld.service
    state: started
    daemon_reload: yes
    enabled: yes
  tags: [firewall, firewalld]

- name: Set firewall zones
  firewalld:
    interface: '{{ item.interface | default(omit) }}'
    zone: '{{ item.zone | default(omit) }}'
    state: '{{ item.state | default("enabled") }}'
    permanent: yes
  loop: '{{ firwalld_rules | default([]) }}'
  loop_control:
    label: '{{ item.name }}'
  tags: [firewall, firewalld]
  notify: Restart firewalld

- name: Set firewall sources
  firewalld:
    zone: '{{ item.zone | default(omit) }}'
    source: '{{ item.sourceips | default(omit) }}'
    state: '{{ item.state | default("enabled") }}'
    permanent: yes
  loop: '{{ firwalld_rules | default([]) }}'
  loop_control:
    label: '{{ item.name }}'
  tags: [firewall, firewalld]
  notify: Restart firewalld

- name: Set firewall rules
  firewalld:
    service: '{{ item.service | default(omit) }}'
    state: '{{ item.state | default("enabled") }}'
    zone: '{{ item.zone | default(omit) }}'
    port: '{{ item.port | default(omit) }}'
    permanent: yes
  loop: '{{ firwalld_rules | default([]) }}'
  tags: [firewall, firewalld]
  notify: Restart firewalld

- name: Ensure handlers are notified now
  meta: flush_handlers
  tags: [firewall, firewalld]

- name: Reload firewalls
  command: firewall-cmd --reload
  changed_when: false
  tags: [firewall, firewalld]