# Role common main
---
- name: Getting all hostkeys
  when: hostvars[item].ansible_facts.ens10 is defined
  run_once: yes
  set_fact:
    all_hostkeys: "{{ all_hostkeys | default([]) + [hostvars[item].ansible_facts.ens10.ipv4.address + ' ssh-rsa ' + hostvars[item].ansible_facts.ssh_host_key_rsa_public] + [hostvars[item].ansible_facts.ens10.ipv4.address + ' ssh-ed25519 ' + hostvars[item].ansible_facts.ssh_host_key_ed25519_public] + [hostvars[item].ansible_facts.ens10.ipv4.address + ' ecdsa-sha2-nistp256 ' + hostvars[item].ansible_facts.ssh_host_key_ecdsa_public] }}"
  with_items: '{{ groups.all }}'
  tags: [common, hostnames]

- name: Install aptitude using apt
  apt:
    name: aptitude
    state: latest
    update_cache: yes
  tags: common

- name: Install required system packages
  apt:
    name: '{{ item }}'
    state: latest
    install_recommends: no
  loop:
    - 'software-properties-common'
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'wget'
    - 'curl'
    - 'tar'
    - 'gzip'
    - 'pass'
    - 'gnupg'
    - 'gnupg2'
    - 'openssl'
    - 'lsb-release'
    - 'python3-pip'
    - 'python3-requests'
    - 'python3-jsondiff'
    - 'python3-yaml'
    - 'unzip'
    - 'git'
  tags: [common, apt]

- name: Install additional packages
  apt:
    name: '{{ item }}'
    state: latest
    install_recommends: no
  loop: '{{ extra_packages }}'
  tags: [common, apt]

- name: Remove specified packages
  apt:
    name: '{{ item }}'
    state: absent
  loop: '{{ delete_packages }}'
  tags: [common, apt]

- name: Set hostnames
  import_tasks: install-hostnames.yml
  tags: [common, hostnames]

- name: Add ssh keys
  import_tasks: shared/set-ssh-keys.yml
  vars:
    ssh_key_list: '{{ common_ssh_keys }}'
  tags: [common, ssh-keys]

- name: Ensure logfile for cron exists
  lineinfile:
    path: /var/log/cron.log
    line: \#Cron Log file
    create: yes
    mode: '0644'
  tags: [common, cron]

- name: Install cron jobs
  import_tasks: shared/install-cron-jobs.yml
  vars:
    cron_jobs: '{{ common_cron_jobs }}'
  tags: [common, cron]
