# Role common main
---
- name: Install aptitude using apt
  apt:
    name: aptitude
    state: latest
    update_cache: yes

- name: install required system packages
  apt:
    name: '{{ item }}'
    state: latest
    install_recommends: no
  loop:
    - 'software-properties-common'
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'wget'
    - 'curl'
    - 'pass'
    - 'gnupg'
    - 'gnupg2'
    - 'openssl'
    - 'lsb-release'
    - 'python3-pip'
    - 'python3-requests'
    - 'python3-jsondiff'
    - 'python3-yaml'
    - 'unzip'
    - 'git'

- name: Install additional packages
  apt:
    name: '{{ item }}'
    state: latest
    install_recommends: no
  loop: '{{ extra_packages }}'

- name: Set hostnames
  include_tasks: install-hostnames.yml

- name: add ssh keys
  include_tasks: install-ssh-keys.yml

- name: Ensure logfile for cron exists
  lineinfile:
    path: /var/log/cron.log
    line: \#Cron Log file
    create: yes
    mode: '0644'

- name: install cron jobs
  include_tasks: shared/install-cron-jobs.yml
  vars:
    cron_jobs: '{{ common_cron_jobs }}'