# Main k8s/hetzner Setup
---
- name: Create a monitoring namespace
  kubernetes.core.k8s:
    name: hcloud
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
  tags: [k8s, k8s-hetzner]

- name: Create Secret
  when: k8s_hetzner_api_key != "none"
  kubernetes.core.k8s:
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: hcloud
        namespace: kube-system
      stringData:
        token: '{{ k8s_hetzner_api_key }}'
        network: '{{ k8s_hetzner_network_name_or_id }}'
  tags: [k8s, k8s-hetzner]

# https://github.com/hetznercloud/hcloud-cloud-controller-manager
- name: Get latest hetzner cloud controller
  when: k8s_hetzner_api_key != "none"
  ansible.builtin.uri:
    url: 'https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/latest/download/ccm{{ "-networks" if (k8s_hetzner_use_ccm_pvt_networks) }}.yaml'
    return_content: true
    status_code: [200, 304]
  register: k8s_intanal_hetzner_cloud_controler_def
  tags: [k8s, k8s-hetzner]

# https://github.com/hetznercloud/csi-driver
- name: Get latest hetzner csi driver
  when: k8s_hetzner_api_key != "none" and k8s_hetzner_install_csi_driver
  ansible.builtin.uri:
    url: https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.2.0/deploy/kubernetes/hcloud-csi.yml
    return_content: true
    status_code: [200, 304]
  register: k8s_intanal_hetzner_csi_driver_def
  tags: [k8s, k8s-hetzner]

- name: Apply Hetzner Cloud Controller
  when: k8s_hetzner_api_key != "none"
  kubernetes.core.k8s:
    namespace: kube-system
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
    state: '{{ "present" if (k8s_hetzner_install_ccm) else "absent" }}'
    definition: "{{ k8s_intanal_hetzner_cloud_controler_def.content | regex_replace('\"--cluster-cidr=.*\"', '\"--cluster-cidr=' + k8s_pod_network_cidr + '\"') }}"
  tags: [k8s, k8s-hetzner]

- name: Apply Hetzner Cloud CSI Driver
  when: k8s_hetzner_api_key != "none" and k8s_hetzner_install_csi_driver
  kubernetes.core.k8s:
    namespace: kube-system
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
    state: present
    definition: '{{ k8s_intanal_hetzner_csi_driver_def.content }}'
  tags: [k8s, k8s-hetzner]

- name: Template Loadbalancer Exporter Manifest
  when: k8s_hetzner_api_key != "none" and k8s_hetzner_install_lb_exporter
  ansible.builtin.template:
    src: hcloud-prom-lb-exporter.yml.j2
    dest: /tmp/hcloud-prom-lb-exporter.yml
    mode: '0644'
  tags: [k8s, k8s-hetzner]

- name: Apply Loadbalancer Exporter Manifest
  when: k8s_hetzner_api_key != "none" and k8s_hetzner_install_lb_exporter
  kubernetes.core.k8s:
    namespace: kube-system
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
    state: present
    src: /tmp/hcloud-prom-lb-exporter.yml
  tags: [k8s, k8s-hetzner]
