# Main k8s Monitoring

- name: Create a monitoring namespace
  k8s:
    name: monitoring
    api_version: v1
    kind: Namespace
    state: present
  tags: [k8s, k8-init, k8s-monitor]

- name: Copy monitoring definitions files
  copy:
    src: files/
    dest: '{{ target_data_dir | default("") }}/srv/monitoring'
  tags: [k8s, k8-init, k8s-monitor]

- name: Copy monitoring config files
  template:
    src: '{{ item }}.j2'
    dest: '{{ target_data_dir | default("") }}/srv/monitoring/{{ item }}'
    mode: '0644'
  loop:
    - grafana-metrics-config.yml
    - grafana-log-config.yml
    - grafana-traces-config.yml
  tags: [k8s, k8-init, k8s-monitor]

- name: Apply Grafana Agent Manifest & K8s Dashboad
  k8s:
    namespace: monitoring
    kubeconfig: '{{ k8s_kubeconfig | default("/etc/kubernetes/admin.conf") }}'
    state: present
    src: '{{ target_data_dir | default("") }}{{ item }}'
  loop:
    - /srv/monitoring/grafana-metrics-config.yml
    - /srv/monitoring/grafana-metrics-agent.yml
    - /srv/monitoring/grafana-log-config.yml
    - /srv/monitoring/grafana-log-agent.yml
    - /srv/monitoring/grafana-traces-config.yml
    - /srv/monitoring/grafana-traces-agent.yml
    - /srv/monitoring/k8s-dashboard.yml
    - /srv/monitoring/k8s-dashboard-user.yml
  tags: [k8s, k8-init, k8s-monitor]

- name: Add prometheus chart repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
  tags: [k8s, k8-init, k8s-monitor]

- name: Deploy Prometheus kube-state-metrics
  kubernetes.core.helm:
    name: ksm
    chart_ref: prometheus-community/kube-state-metrics
    update_repo_cache: true
    release_namespace: monitoring
    state: present
    create_namespace: true
    values:
      image:
        tag: v2.7.0
  tags: [k8s, k8-init, k8s-monitor]

- name: Deploy Prometheus node-exporter
  kubernetes.core.helm:
    name: prometheus-node-exporter
    chart_ref: prometheus-community/prometheus-node-exporter
    update_repo_cache: true
    release_namespace: monitoring
    state: present
    create_namespace: true
    values: {}
  tags: [k8s, k8-init, k8s-monitor]
