# Add users to docker group
---
- name: Ensue users are created and added to the Docker group
  ansible.builtin.user:
    name: '{{ item }}'
    groups: [docker]
    append: true
    state: present
  with_items: '{{ docker_users }}'
  tags: [docker, docker-user]
