# Log into regestries
---

- name: Log into Docker registries
  no_log: True
  docker_login:
    registry_url: '{{ item.regestry | default("https://index.docker.io/v1/") }}'
    username: '{{ item.username }}'
    password: '{{ item.password }}'
    reauthorize: yes
  loop: '{{ docker_regesties }}'
  loop_control:
    label: '{{ item.regestry | default("https://index.docker.io/v1/") }}'
  tags: [docker, docker-regestry]
