# Log into regestries
---

- name: Log into docker registry
  docker_login:
    registry_url: '{{ item.regestry | default("https://index.docker.io/v1/") }}'
    username: item.username
    password: item.MySuperSecurPW
    reauthorize: yes
  loop: '{{ docker_regesties }}'