# Install Docker
---
- name: Install needed packages
  apt:
    name: ['ca-certificates', 'curl', 'gnupg', 'lsb-release', 'cifs-utils']
    state: present
    update_cache: yes
    install_recommends: no
  tags: [docker, docker-install]

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_facts.distribution | lower }}/gpg
    state: present
  tags: [docker, docker-install]

- name: Add Docker repository
  apt_repository:
    repo: 'deb https://download.docker.com/linux/{{ ansible_facts.distribution | lower }} {{ ansible_facts.lsb.codename }} stable'
    update_cache: yes
    state: present
    filename: docker
  tags: [docker, docker-install]

- name: Install docker
  apt:
    state: present
    install_recommends: no
    name:
      - 'containerd.io'
      - 'docker-{{ docker_edition }}'
      - 'docker-{{ docker_edition }}-cli'
      - 'python3-setuptools'
      - 'python3-jsondiff'
      - 'python3-docker'
      - 'python3-yaml'
      - 'gnupg2'
      - 'pass'
  tags: [docker, docker-install]

- name: Test Docker
  docker_host_info:
    verbose_output: yes
  register: docker_facts
  tags: [docker, docker-install]

- name: Install Loki log driver
  when: docker_install_loki_log_plugin | bool
  community.docker.docker_plugin:
    plugin_name: grafana/loki-docker-driver:latest
    state: present
    alias: loki
  tags: [docker, docker-install]

- name: Enable Loki log driver
  when: docker_install_loki_log_plugin | bool
  community.docker.docker_plugin:
    plugin_name: loki
    state: enable
  tags: [docker, docker-install]

- name: Ensure /etc/docker/ directory exists
  file:
    path: /etc/docker
    state: directory
    mode: 0755
  when: docker_daemon_options.keys() | length > 0
  tags: [docker, docker-install, docker-deamon]

- name: Configure Docker daemon options
  copy:
    content: '{{ docker_daemon_options | to_nice_json }}'
    dest: /etc/docker/daemon.json
    mode: 0644
  when: docker_daemon_options.keys() | length > 0
  notify: Restart Docker
  tags: [docker, docker-install, docker-deamon]

- name: Ensure Docker is started and enabled at boot
  service:
    name: docker
    state: started
    enabled: yes
  tags: [docker, docker-install, docker-deamon]

- name: Ensure handlers are notified now
  meta: flush_handlers
  tags: [docker, docker-install, docker-deamon]
