# Main Docker Setup
---
- name: Install Docker
  import_tasks: install-docker.yml
  tags: [docker, docker-install]

- name: Log into regestry
  import_tasks: docker-login.yml
  tags: [docker, docker-regestry]

- name: Docker-Compose install
  include_tasks: install-compose.yml
  when: docker_install_compose | bool
  tags: [docker, docker-compose]

- name: Docker user setup
  import_tasks: docker-users.yml
  tags: [docker, docker-user]

- name: Setup SWARM
  include_tasks: docker-swarm.yml
  when: docker_init_swarm | bool
  tags: [docker, docker-swarm, docker-tags]

- name: Install Portainer
  include_tasks: docker-portainer.yml
  when: docker_install_portainer | bool
  tags: [docker, docker-portainer]

- name: Setup cron jobs
  include_tasks: shared/install-cron-jobs.yml
  vars:
    cron_jobs: '{{ docker_cron_jobs }}'
  tags: [docker, cron]
