# Main Docker Setup
---
- name: Install docker
  include_tasks: install-docker.yml

- name: Log into regestry
  include_tasks: docker-login.yml
  when: docker_regesties | length > 0

- name: Docker-Compose install
  include_tasks: install-compose.yml
  when: docker_install_compose | bool

- name: Docker user setup
  include_tasks: docker-users.yml
  when: docker_users | length > 0

- name: Setup SWARM
  include_tasks: docker-swarm.yml
  when: docker_init_swarm | bool

- name: Install Portainer
  include_tasks: docker-portainer.yml
  when: docker_install_portainer | bool

- name: Setup cron jobs
  include_tasks: shared/install-cron-jobs.yml
  vars:
    cron_jobs: '{{ docker_cron_jobs }}'
