# Start traefik
---
- name: Enable Traefik service
  when: traefik_use_docker | bool != true
  systemd:
    name: traefik.service
    state: started
    daemon_reload: yes
    enabled: yes
  notify: Restart traefik
  tags: [ingress, traefik]

- name: Verify Traefik status
  when: traefik_use_docker | bool != true
  service:
    name: traefik
    state: started
  tags: [ingress, traefik]