# Start traefik
---
- name: Copy docker-compose file
  when: traefik_use_docker | bool
  template:
    src: docker-compose-traefik.yml.j2
    dest: /srv/docker-compose-traefik.yml
  tags: [ingress, traefik]

- name: Init a new swarm
  when: traefik_use_docker | bool
  docker_swarm:
    advertise_addr: '{{ ansible_host }}'
    state: present
  tags: [ingress, traefik]

- name: Create docker network
  when: traefik_use_docker | bool
  docker_network:
    name: ingress_net
    driver: overlay
    attachable: yes
    driver_options:
      com.docker.network.driver.mtu: 1450
  tags: [ingress, traefik]

- name: Deploy mgmt-stack [via docker stack]
  when: traefik_use_docker | bool
  docker_stack:
    state: present
    name: ingress
    resolve_image: always
    with_registry_auth: yes
    compose: /srv/docker-compose-traefik.yml
  tags: [ingress, traefik]
