# Install mgmt stack
---

- name: Configuring nginx compose|stack files
  template:
    src: mgmt-stack-nginx.yml.j2
    dest: '{{ mgmt_dst_config_files }}mgmt-stack-nginx.yml'
    mode: '0644'
  tags: [mgmt, mgmt-stack, mgmt-nginx]

- name: Creating hosts for nginx
  template:
    src: 'nginx-site.conf.j2'
    dest: '{{ mgmt_dst_config_files }}nginx/conf.d/{{ nginx_vhost.host }}.conf'
    mode: '0644'
  loop: '{{ mgmt_nginx_sites }}'
  loop_control:
    loop_var: nginx_vhost
  notify: Reload nginx
  tags: [mgmt, mgmt-stack, mgmt-nginx]

- name: Deploy mgmt-stack [via docker stack]
  when: mgmt_use_swarm_mode | bool
  docker_stack:
    state: present
    name: '{{ mgmt_docker_stack_name }}'
    resolve_image: always
    with_registry_auth: yes
    compose: '{{ mgmt_dst_config_files }}mgmt-stack-nginx.yml'
  tags: [mgmt, mgmt-stack, mgmt-nginx]

- name: Wait for containers to start
  wait_for:
    port: 80
    delay: 5
    timeout: 30
  tags: [mgmt, mgmt-stack, mgmt-nginx]

- name: Get nginx container-name
  command: "docker ps -f name={{ mgmt_docker_stack_name }}_nginx --format {{ '{{' }}.ID{{ '}}' }}"
  changed_when: false
  register: nginx_containerid
  tags: [mgmt, mgmt-stack, mgmt-nginx]

- name: Ensure handlers are notified now
  meta: flush_handlers
  tags: [mgmt, mgmt-stack, mgmt-nginx]

- name: Install certbot in container
  when: mgmt_proxy_use_tls | bool
  community.docker.docker_container_exec:
    container: '{{ nginx_containerid.stdout }}'
    command: /bin/sh -c "apk add certbot certbot-nginx"
  changed_when: false
  tags: [mgmt, mgmt-stack, mgmt-nginx]

- name: Run Certbot
  when: mgmt_proxy_use_tls | bool
  community.docker.docker_container_exec:
    container: '{{ nginx_containerid.stdout }}'
    command: 'certbot --nginx -d {{ nginx_vhost.host }} --agree-tos --non-interactive -m {{ mgmt_certbot_mail }}'
  register: mgmt_cert_res
  loop: '{{ mgmt_nginx_sites }}'
  loop_control:
    loop_var: nginx_vhost
    label: '{{ nginx_vhost.host }}'
  notify: Reload nginx
  tags: [mgmt, mgmt-stack, mgmt-nginx]

- name: DEBUG
  when: mgmt_proxy_use_tls | bool
  debug:
    msg: '{{ item.stdout_lines }}'
  loop: '{{ mgmt_cert_res.results }}'
  loop_control:
    label: '{{ item.host.nginx_vhost.host }}'
  tags: [mgmt, mgmt-stack, mgmt-nginx]

- name: Ensure handlers are notified now
  meta: flush_handlers
  tags: [mgmt, mgmt-stack, mgmt-nginx]
