# Install aws-cli & azcopy
---
- name: Install aws-cli
  ansible.builtin.apt:
    name: awscli
    state: latest
    install_recommends: false
  tags: [mgmt, backup]

- name: Check if azcopy is installed
  ansible.builtin.command: 'azcopy --version'
  register: azcopy_check_result
  changed_when: false
  failed_when: false
  tags: [mgmt, backup]

- name: Download and unarchive azcopy
  unarchive:
    src: https://aka.ms/downloadazcopy-v10-linux
    dest: /tmp
    remote_src: true
  tags: [mgmt, backup]

- name: Install azcopy
  when: azcopy_check_result.stdout == ""
  ansible.builtin.shell: |
    mv /tmp/azcopy_linux*/azcopy /usr/local/bin/azcopy
  tags: [mgmt, backup]

- name: Test azcopy
  ansible.builtin.command: "azcopy --version"
  changed_when: "false"
  tags: [mgmt, backup]

- name: Check if minio mc is installed
  ansible.builtin.command: 'mc --version'
  register: mc_check_result
  changed_when: false
  failed_when: false
  tags: [mgmt, backup]

- name: Install minio mc
  when: mc_check_result.stdout == ""
  ansible.builtin.get_url:
    url: https://dl.min.io/client/mc/release/linux-amd64/mc
    dest: /usr/local/bin/mc
    mode: '0755'
  tags: [mgmt, backup]

- name: Test minio mc
  ansible.builtin.command: "mc --version"
  changed_when: "false"
  tags: [mgmt, backup]
