# Install mgmt stack
---
- name: Install pip3
  when: mgmt_use_swarm_mode
  apt:
    name: '{{ item }}'
    state: latest
  loop: ['python3-pip', 'libffi-dev']

- name: Install compose package
  when: mgmt_use_swarm_mode | bool != true
  pip:
    name: docker-compose

- name: Copy MGMT compose|stack base files
  copy:
    src: 'srv/'
    dest: '{{ mgmt_dst_config_files }}'
    owner: root
    group: root

- name: Copy MGMT compose|stack custom files
  copy:
    src: '{{ mgmt_src_config_files }}'
    dest: '{{ mgmt_dst_config_files }}'
    owner: root
    group: root

- name: Configuring compose|stack files
  template:
    src: '{{ item }}.j2'
    dest: '{{ mgmt_dst_config_files }}/{{ item }}'
    mode: '0644'
  loop: '{{ mgmt_services_to_install }}'

- name: Setting Grafana password
  no_log: true
  template:
    src: 'grafana.j2'
    dest: '{{ mgmt_dst_config_files }}/mgmt-grafana/grafana_admin_pw.txt'
    mode: '0644'

- name: Deploy mgmt-stack [via docker-compose]
  when: mgmt_use_swarm_mode | bool != true
  docker_compose:
    project_name: '{{ mgmt_docker_stack_name }}'
    remove_orphans: yes
    project_src: '{{ mgmt_dst_config_files }}'
    files: '{{ mgmt_services_to_install | list }}'

- name: Init a new swarm
  when: mgmt_use_swarm_mode | bool
  docker_swarm:
    advertise_addr: '{{ ansible_host }}'
    state: present

- name: Create absolut paths for stack files
  when: mgmt_use_swarm_mode | bool
  set_fact:
    mgmt_compose_files_stack: '{{ mgmt_compose_files_stack | default([]) + ["".join((mgmt_dst_config_files,item))] }}'
  loop: '{{ mgmt_services_to_install | list}}'

- name: Deploy mgmt-stack [via docker stack]
  when: mgmt_use_swarm_mode | bool
  docker_stack:
    state: present
    name: '{{ mgmt_docker_stack_name }}'
    resolve_image: always
    with_registry_auth: yes
    compose: '{{ mgmt_compose_files_stack | list }}'

- name: Copy wireguard config
  when: mgmt_use_wireguard | bool
  template:
    src: mgmt-stack-wiregurd.yml.j2
    dest: '{{ mgmt_dst_config_files }}/mgmt-stack-wiregurd.yml'
    mode: '0644'

- name: Deploy wireguard-stack
  when: mgmt_use_wireguard | bool
  docker_compose:
    project_name: monitor-stack
    remove_orphans: yes
    project_src: '{{ mgmt_dst_config_files }}'
    files: ['mgmt-stack-wiregurd.yml']

- name: Sleep for 45 seconds and continue with play
  wait_for:
    timeout: 45

- name: Shows stack info
  community.docker.docker_stack_info:
  when: mgmt_use_swarm_mode | bool != true
  register: mgmt_docker_stack_info

- name: Show stack info
  when: mgmt_use_swarm_mode | bool != true
  debug:
    var: mgmt_docker_stack_info.results

