# Install mgmt stack
---
- name: Copy MGMT compose|stack base files
  copy:
    src: 'srv/'
    dest: '{{ mgmt_dst_config_files }}'
    owner: root
    group: root

- name: Copy MGMT compose|stack extra files
  copy:
    src: '{{ mgmt_src_config_files }}'
    dest: '{{ mgmt_dst_config_files }}'
    owner: root
    group: root

- name: Configuring compose|stack files
  template:
    src: '{{ item }}.j2'
    dest: '{{ mgmt_dst_config_files }}/{{ item }}'
    mode: '0644'
  loop: '{{ mgmt_services_to_install }}'

- name: Setting Grafana password
  template:
    src: 'grafana.j2'
    dest: '{{ mgmt_dst_config_files }}/mgmt-grafana/grafana_admin_pw.txt'
    mode: '0644'

- name: Install pip3
  when: mgmt_use_swarm_mode | bool != true
  apt:
    name: python3-pip
    state: latest

- name: Install compose package
  when: mgmt_use_swarm_mode | bool != true
  pip:
    name: docker-compose

- name: Deploy mgmt-services via compose
  when: mgmt_use_swarm_mode | bool != true
  environment:
    MONGODB_SERVER: '{{ mgmt_mongodb_target_host }}'
    WAF_HOST: '{{ mgmt_waf_target_host }}'
    SQL_HOST: '{{ mgmt_sql_taget_host }}'
  docker_compose:
    project_name: monitor-stack
    remove_orphans: yes
    project_src: '{{ mgmt_dst_config_files }}'
    files: '{{ mgmt_services_to_install | list }}'

- name: Init a new swarm
  when: mgmt_use_swarm_mode | bool
  docker_swarm:
    advertise_addr: "{{ ansible_host }}"
    state: present

- name: Create absolut paths for stack files
  when: mgmt_use_swarm_mode | bool
  set_fact:
    mgmt_compose_files_stack: '{{ mgmt_compose_files_stack | default([]) + ["".join((mgmt_dst_config_files,item))] }}'
  loop: "{{ mgmt_services_to_install | list}}"

- name: Deploy mgmt-stack from a compose file
  when: mgmt_use_swarm_mode | bool
  environment:
    MONGODB_SERVER: '{{ mgmt_mongodb_target_host }}'
    WAF_HOST: '{{ mgmt_waf_target_host }}'
    SQL_HOST: '{{ mgmt_sql_taget_host }}'
  docker_stack:
    state: present
    name: monitor-stack
    resolve_image: always
    with_registry_auth: yes
    compose: '{{ mgmt_compose_files_stack | list }}'

- name: Sleep for 45 seconds and continue with play
  wait_for:
    timeout: 45

- name: Shows stack info
  community.docker.docker_stack_info:
  when: mgmt_use_swarm_mode | bool != true
  register: mgmt_docker_stack_info

- name: Show stack info
  when: mgmt_use_swarm_mode | bool != true
  debug:
    var: mgmt_docker_stack_info.results

