# Main mgmt setup
---
- name: Setup sshd
  include_tasks: setup-sshd.yml

- name: Setup fail2ban
  include_tasks: setup-fail2ban.yml

- name: Install aws-cli
  apt:
    name: awscli
    state: latest
    install_recommends: no

- name: Install azcopy
  include_tasks: install-azcopy.yml

- name: Copy script for backup archival
  copy:
    src: 'srv/archive-db-backups.sh'
    dest: '{{ mgmt_dst_config_files }}'
    owner: root
    group: root

- name: Run docker install
  include_role:
    name: docker

- name: Ensure handlers are notified now
  meta: flush_handlers

- name: Install mgmt stack
  include_tasks: install-mgmt-stack.yml

- name: Setup portainer
  when: mgmt_setup_portainer | bool
  include_tasks: setup-protainer.yml

- name: Setup grafana
  when: mgmt_setup_grafana | bool
  include_tasks: setup-grafana.yml
