# Reconfig sshd
---
- name: Setup ssh options
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?{{ item }}$'
    line: '{{ item }}'
  loop: '{{ sshd_options }}'
  notify: Restart SSHD
  tags: [mgmt, ssh]

- name: Disable ssh password login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: Restart SSHD
  tags: [mgmt, ssh]

- name: Disable ssh X11
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?X11Forwarding*'
    line: 'X11Forwarding no'
  notify: Restart SSHD
  tags: [mgmt, ssh]

- name: Set ssh banner
  template:
    src: ssh_banner.txt.j2
    dest: /etc/ssh/mgmt_banner.txt
    mode: '0644'
  notify: Restart SSHD
  tags: [mgmt, ssh]

- name: Enable ssh banner
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#Banner none*'
    line: 'Banner /etc/ssh/mgmt_banner.txt'
  notify: Restart SSHD
  tags: [mgmt, ssh]

- name: Adding JumpHost user {{ mgmt_jumphost_user }}
  user:
    name: '{{ mgmt_jumphost_user }}'
    comment: '{{ mgmt_user_comment | default("JumpHost user")}}'
    shell: /usr/bin/bash
    create_home: no
    state: present
  tags: [mgmt, ssh]

- name: Ensure ssh directory exists
  file:
    path: '/home/{{ mgmt_jumphost_user }}/.ssh'
    state: directory
    mode: 0600
  tags: [mgmt, ssh, ssh-keys]

- name: Add ssh keys
  import_tasks: shared/set-ssh-keys.yml
  vars:
    ssh_key_list: '{{ mgmt_ssh_keys }}'
  tags: [mgmt, ssh, ssh-keys]
