# Setup portainer
---
- name: Wait for portainer to start
  ansible.builtin.wait_for:
    port: 9000
    delay: 5
    timeout: 30
  tags: [mgmt, portainer]

- name: Set Portainer Admin-PW
  ansible.builtin.uri:
    url: 'http://{{ mgmt_portainer_host }}/api/users/admin/init'
    method: POST
    body: "{\"Username\":\"admin\",\"Password\":\"{{ mgmt_portainer_pw }}\"}"
    body_format: json
    headers:
      Content-Type: "application/json"
  register: mgmt_portainer_api_res
  failed_when: "mgmt_portainer_api_res.status != 200 and mgmt_portainer_api_res.status != 409"
  ignore_errors: true
  tags: [mgmt, portainer]

- name: Get Portainer Token
  ignore_errors: true
  ansible.builtin.uri:
    url: 'http://{{ mgmt_portainer_host }}/api/auth'
    method: POST
    body: "{\"Username\":\"admin\",\"Password\":\"{{ mgmt_portainer_pw }}\"}"
    body_format: json
    headers:
      Content-Type: "application/json"
  register: mgmt_portainer_api_res
  tags: [mgmt, portainer]

- name: Add portainer nodes
  ansible.builtin.uri:
    url: 'http://{{ mgmt_portainer_host }}/api/endpoints'
    method: POST
    body_format: form-multipart
    body:
      Name: '{{ item.key }}'
      EndpointCreationType: '2'
      URL: '{{ item.value }}'
    headers:
      Content-Type: "multipart/form-data; boundary=<calculated when request is sent>"
      Authorization: 'Bearer {{ mgmt_portainer_api_res.json.jwt }}'
  with_dict: "{{ mgmt_portainer_nodes }}"
  ignore_errors: true
  tags: [mgmt, portainer]
