# Reconfig sshd
---

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: latest
  tags: [mgmt, ssh]

- name: Start fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  tags: [mgmt, ssh]
