# Reconfig sshd
---

- name: Install fail2ban
  apt:
    name: fail2ban
    state: latest
  tags: [mgmt, mgmt-stack]

- name: Start fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
  tags: [mgmt, mgmt-stack]