# Install nginx-hosts
---
- name: Check nginx is installed
  ansible.builtin.command: nginx -V
  changed_when: false
  tags: [php, php-nginx]

- name: Copy NGINX conf files
  ansible.builtin.copy:
    src: '{{ php_nginx_src_config_dir }}'
    dest: /etc/nginx/
    owner: root
    group: root
    mode: '0644'
  tags: [php, php-nginx]

- name: Copy default nginx server conf file
  when: php_nginx_use_default_server | bool
  ansible.builtin.template:
    src: nginx-default-server.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: '0644'
  tags: [php, php-nginx]

- name: Copy Hosts to nginx
  when: php_nginx_use_default_server | bool != true
  ansible.builtin.copy:
    src: '{{ php_nginx_hosts_src_config_dir }}'
    dest: /etc/nginx/conf.d/
    owner: root
    group: root
    mode: '0644'
  tags: [php, php-nginx]

- name: Check nginx syntax
  ansible.builtin.command: nginx -t
  register: res
  changed_when: false
  failed_when: '"warn" is in res.stderr_lines or "emerg" is in res.stderr_lines or res.rc != 0'
  tags: [php, php-nginx]

- name: Reload nginx
  ansible.builtin.command: nginx -s reload
  tags: [php, php-nginx]

- name: Verify Nginx is started
  ansible.builtin.service:
    name: nginx
    state: started
  tags: [php, php-nginx]
