---
k8s_version: 1.24.4
k8s_shared_api_server_endpoint: '{{ ansible_facts.default_ipv4.address }}'
k8s_pod_network_cidr: 10.244.0.0/16
k8s_cert_extra_sans: '{{ ["127.0.0.1"] + ansible_facts.all_ipv4_addresses }}'

k8s_kubeadm_opts: ''
k8s_init_opts: ''
k8_cert_key: none

# Taints
k8s_taints:
  - node: '{{ ansible_facts.hostname }}'
    key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
    state: absent

######### Certmanager #########
k8s_install_certmanager: yes
k8s_certmanager_helm_values:
  installCRDs: true

######### CNI #########
# Which CNI flannel, calico or cilium
k8s_cni: flannel
k8s_cilium_helm_values: {}
k8s_calico_helm_values:
  installation:
    cni:
      type: Calico
    calicoNetwork:
      ipPools:
      - cidr: '{{ k8s_pod_network_cidr }}'
