---
k8s_version: 1.24.4
k8s_api_server: '{{ ansible_facts.default_ipv4.address }}'

k8s_pod_network_cidr: 10.244.0.0/16
k8s_cert_extra_sans: '{{ ["127.0.0.1", "10.10.0.2", "10.10.0.3", "10.10.0.4"] + ansible_facts.all_ipv4_addresses }}'

k8s_kubeadm_opts: ''
k8s_init_opts: ''
k8_cert_key: none

k8s_taints:
  - node: '{{ ansible_facts.hostname }}'
    key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
    state: absent

######### CNI #########
# Which CNI flannel or calico
k8s_cni: flannel
k8s_calico_helm_values:
  installation:
    cni:
      type: Calico
    calicoNetwork:
      ipPools:
      - cidr: '{{ k8s_pod_network_cidr }}'
