---
k8s_version: 1.24.4
k8s_api_server: '{{ ansible_facts.default_ipv4.address }}'
k8s_pod_network_cidr: 10.244.0.0/16
k8s_cert_extra_sans: '{{ (["127.0.0.1", "10.10.0.2", "10.10.0.3", "10.10.0.4"] + ansible_facts.all_ipv4_addresses) | unique | join(",") }}'


k8s_kubeadm_opts: ''
k8s_init_opts: ''

k8s_install_helm: yes
k8_cert_key: none
