version: '3.7'

services:
  mongo-express:
    image: mongo-express:latest
    environment:
      - TZ=Europe/Berlin
      - ME_CONFIG_MONGODB_SERVER=${MONGODB_HOST}
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
