version: '3.7'

services:
  loki:
    image: grafana/loki:latest
    environment:
      - TZ=Europe/Berlin
    networks:
      - mgmt_net
    ports:
      - target: 3100
        published: 3100
        protocol: tcp
        mode: host
    volumes:
      - loki-data:/loki
    configs:
      - source: loki-conf
        target: /mnt/config/loki-config.yml

  grafana:
    image: grafana/grafana:latest
    environment:
      - TZ=Europe/Berlin
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/mnt/config/admin_password
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,digrich-bubblechart-panel,alexanderzobnin-zabbix-app,grafana-worldmap-panel
    networks:
      - mgmt_net
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - grafana-data:/var/lib/grafana
    configs:
      - source: grafana-admin-pw
        target: /mnt/config/admin_password

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command: -nginx.scrape-uri=http://${WAF_HOST}/nginx_status
    networks:
      - mgmt_net

  prometheus:
    image: prom/prometheus:latest
    environment:
      - TZ=Europe/Berlin
    networks:
      - mgmt_net
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/data
    configs:
      - source: prometheus-conf
        target: /etc/prometheus/prometheus.yml

  portainer:
    image: portainer/portainer-ce:latest
    command: --tlsskipverify
    environment:
      - TZ=Europe/Berlin
    networks:
      - mgmt_net
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
      - target: 9443
        published: 9443
        protocol: tcp
        mode: host
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]

configs:
  loki-conf:
    # file: ./mgmt-loki/loki-config.yml
    file: /srv/mgmt-loki/loki-config.yml
  grafana-admin-pw:
    # file: ./mgmt-grafana/grafana_admin_pw.txt
    file: /srv/mgmt-grafana/grafana_admin_pw.txt
  prometheus-conf:
    # file: ./mgmt-prometheus/prometheus.yml
    file: /srv/mgmt-prometheus/prometheus.yml
volumes:
  loki-data:
  grafana-data:
  prometheus-data:
  portainer-data:
  promtail-data:

networks:
  mgmt_net:
    driver: overlay
    attachable: true
    driver_opts:
      com.docker.network.driver.mtu: 1450
      # Workaround for Hetzner and GCE networks
      # See: https://github.com/portainer/portainer/issues/4962