# K8s install certmanager

# TODO make sure helm is installed
- name: Add GitLab Helm repo
  kubernetes.core.helm_repository:
    name: reddvid-test
    username: gitlab-hcloude-helm
    password: ***REMOVED***
    repo_url: https://gitlab.com/api/v4/projects/40808451/packages/helm/stable
  no_log: true
  tags: [k8s, k8-deploy, helm-deploy]

- name: Deploy App
  kubernetes.core.helm:
    name: myapp
    state: present
    update_repo_cache: true
    kubeconfig: /etc/kubernetes/admin.conf
    chart_version: 0.1.2
    chart_ref: reddvid-test/reddvid
    release_namespace: my-app
    create_namespace: true
    wait: true
    # values: '{{ k8s_app_helm_values | default({}) }}'
    values:
      service:
        annotations:
          # load-balancer.hetzner.cloud/name: "k8s-worker-lb"
      ingress:
        enabled: yes
        className: nginx
        annotations:
          # kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-staging
        hosts:
          - host: reddvid-k8s.henrikgerdes.me
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: reddvid-k8s
            hosts:
              - reddvid-k8s.henrikgerdes.me
      image:
        repository: nginx
        tag: latest

  tags: [k8s, k8-deploy, helm-deploy]
