# K8s install certmanager

# TODO make sure helm is installed
- name: Add GitLab Helm repo
  kubernetes.core.helm_repository:
    name: '{{ k8s_app_helm_repo.name}}'
    username: '{{ k8s_app_helm_repo.username}}'
    password: '{{ k8s_app_helm_repo.password}}'
    repo_url: '{{ k8s_app_helm_repo.repo_url}}'
  no_log: true
  tags: [k8s, k8s-deploy, helm-deploy]

- name: Deploy App
  kubernetes.core.helm:
    name: myapp
    state: present
    # state: absent
    update_repo_cache: true
    kubeconfig: /etc/kubernetes/admin.conf
    chart_version: 0.1.2
    chart_ref: reddvid-test/reddvid
    release_namespace: my-app
    create_namespace: true
    wait: true
    values: '{{ k8s_app_helm_values | default({}) }}'
  tags: [k8s, k8s-deploy, helm-deploy]
