services:
  postgres:
    image: postgres:13-bullseye
    hostname: postgres-testdb
    container_name: postgres-test
    restart: always
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=3KdaYl8Y2pa7T8YHShdg
      - POSTGRES_DB=vaultwarden
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    tmpfs:
      - /tmp
      - /var/run/postgresql

volumes:
  postgres-data:
