version: '3.7'

services:
  sql-exporter:
    image: prom/mysqld-exporter:latest
    hostname: sql-exporter
    environment:
      - TZ=Europe/Berlin
      - DATA_SOURCE_NAME=exporter:au]RJ7dD!Sj59FSi@(db:3306)/
    ports:
      - 9104:9104

# mgmt_sql_exporter_connection_string: '{{ mgmt_sql_exporter_user + ":" + mgmt_sql_exporter_pw + "@" + "(" + mgmt_sql_taget_host + ":" + mgmt_sql_taget_port | string +")" }}'
# exporter:au]RJ7dD!Sj59FSi@(db:3306)


  db:
    image: mariadb
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=yes
      - MYSQL_USER=tester
      - MYSQL_PASSWORD=tester
      - MYSQL_DATABASE=testdb
    ports:
      - 3306:3306
    # volumes:
    #   - maria_db_data:/var/lib/mysql

  myadmin:
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - TZ=Europe/Berlin
      - UPLOAD_LIMIT=2G
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=yes
    ports:
      - 8888:80

volumes:
  maria_db_data:
