version: '3.7'

services:
  port-ui:
    image: portainer/portainer-ce:latest
    hostname: henrik-thinkpad-portainer
    restart: always
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8008:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - portainer-data:/data

  port-agent:
    image: portainer/agent:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

volumes:
  portainer-data:
