---
hetzner_api_key: '{{ lookup("env","HETZNER_API_KEY") }}'
hetzner_default_server_size: cx11
hetzner_default_server_location: nbg1
hetzner_default_server_image: debian-11
hetzner_default_server_state: present
hetzner_default_vnet_name: my-network
hetzner_inventroy_dst: '{{ inventory | default(inventory_dir + "/ansible-inventory.yml") }}'
ansible_default_port: 22
ansible_default_user: root
hetzner_use_internal_ip: no
# Floting IP mapping
hetzner_floating_ip_mapping: []
# Example
# hetzner_floating_ip_mapping:
#   - server_name: waf
#     floting_ip_name: ingres-ip

# VM configs
hetzner_vms: []
# Example
# hetzner_vms:
#   - name: waf
#     image: debian-11
#     location: nbg1
#     size: cx11
#     intern_ip: 10.10.0.2
#     groups:
#       - docker_hosts
#       - gateways
#     state: present
#     ssh_keys:
#       - <Key_name>

# Groups can be:
# docker_hosts
# mgmt_hosts
# gateways
# databases

# Inventroy to generate
hetzner_inventory:
  all:
    hosts: {}
    vars:
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    children:
      docker_hosts:
        hosts:
      mgmt_hosts:
        hosts:
      gateways:
        hosts:
      databases:
        hosts:
# Example
# hetzner_inventory:
#   all:
#     hosts:
#       test-host:
#         ansible_port: 22
#         ansible_host: 127.0.0.1
#         ansible_user: root
#     vars:
#       ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q root@159.69.107.51"'
#   children:
#     docker_hosts: []
#     mgmt_hosts: []
#     gateways: []
#     databases: []

hetzner_firewalls:
  - name: block-all
  - name: ssh-only
    rules:
    - direction: in
      description: ssh own
      protocol: tcp
      port: 2223
      source_ips:
        - 0.0.0.0/0
        - ::/0
    - direction: in
      description: ssh default
      protocol: tcp
      port: 22
      source_ips:
        - 0.0.0.0/0
        - ::/0
  - name: http/https
    rules:
    - direction: in
      protocol: tcp
      port: 80
      description: allow http
      source_ips:
        - 0.0.0.0/0
        - ::/0
    - direction: in
      protocol: tcp
      port: 443
      description: allow https
      source_ips:
        - 0.0.0.0/0
        - ::/0