---
# Influx settings

# Install via Docker
influx_use_docker: yes
influx_docker_version: 2.1-alpine

# Init
influx_root_user: root
influx_organization: example-org
influx_root_bucket: example-bucket
influx_root_pw: mySuperSecureAdminPW
influx_root_token: my-super-secret-auth-token
influx_bind_hostname: '{{ ansible_default_ipv4.address }}'
influx_listen_port: 8086
influx_listen_addr: '{{ influx_bind_hostname }}:{{ influx_listen_port }}'

influx_db_backup_script: "{{'backup_db-docker.sh' if (influx_use_docker) else 'backup_db-docker.sh'}}"

# DB setup
influx_setups:
  - db: test1
    user: user1
    pw: mysecurepw1


# For backup
influx_cron_jobs:
  - name: Dump DB as backup
    job: bash /db_dumps/backup_db.sh
    weekday: '*'
    month: '*'
    minute: '30'
    hour: '02'
    day: '*'
    state: present
    user: null
